/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const filterControllerCreateBodyNameMax = 255;

export const filterControllerCreateBodyDescriptionMax = 1024;

export const filterControllerCreateBodyIsActiveDefault = true;
export const filterControllerCreateBodyActionContentWarningOneMax = 512;

export const FilterControllerCreateBody = zod.object({
  action: zod.object({
    contentWarning: zod.union([
      zod.string().max(filterControllerCreateBodyActionContentWarningOneMax),
      zod.null(),
    ]),
    type: zod.enum(['blur', 'markRead', 'hide']),
  }),
  conditions: zod.object({
    authors: zod.array(zod.string()).optional(),
    categories: zod.array(zod.string()).optional(),
    contentContains: zod.array(zod.string()).optional(),
    feeds: zod.array(zod.string()).optional(),
    keywords: zod.array(zod.string()).optional(),
    titleContains: zod.array(zod.string()).optional(),
  }),
  description: zod
    .string()
    .max(filterControllerCreateBodyDescriptionMax)
    .optional(),
  isActive: zod.boolean().default(filterControllerCreateBodyIsActiveDefault),
  name: zod.string().min(1).max(filterControllerCreateBodyNameMax),
});

export const filterControllerFindAllResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const filterControllerFindAllResponseNameOneMax = 255;

export const filterControllerFindAllResponseDescriptionMax = 1024;

export const filterControllerFindAllResponseIsActiveDefault = true;
export const filterControllerFindAllResponseActionContentWarningOneMax = 512;

export const FilterControllerFindAllResponseItem = zod.object({
  action: zod.object({
    contentWarning: zod.union([
      zod
        .string()
        .max(filterControllerFindAllResponseActionContentWarningOneMax),
      zod.null(),
    ]),
    type: zod.enum(['blur', 'markRead', 'hide']),
  }),
  conditions: zod.object({
    authors: zod.array(zod.string()).optional(),
    categories: zod.array(zod.string()).optional(),
    contentContains: zod.array(zod.string()).optional(),
    feeds: zod.array(zod.string()).optional(),
    keywords: zod.array(zod.string()).optional(),
    titleContains: zod.array(zod.string()).optional(),
  }),
  description: zod
    .string()
    .max(filterControllerFindAllResponseDescriptionMax)
    .optional(),
  id: zod.uuid().stringFormat('uuid', filterControllerFindAllResponseIdRegExp),
  isActive: zod
    .boolean()
    .default(filterControllerFindAllResponseIsActiveDefault),
  name: zod.union([
    zod.string().max(filterControllerFindAllResponseNameOneMax),
    zod.null(),
  ]),
});
export const FilterControllerFindAllResponse = zod.array(
  FilterControllerFindAllResponseItem,
);

export const FilterControllerFindOneParams = zod.object({
  id: zod.string(),
});

export const filterControllerFindOneResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const filterControllerFindOneResponseNameOneMax = 255;

export const filterControllerFindOneResponseDescriptionMax = 1024;

export const filterControllerFindOneResponseIsActiveDefault = true;
export const filterControllerFindOneResponseActionContentWarningOneMax = 512;

export const FilterControllerFindOneResponse = zod.object({
  action: zod.object({
    contentWarning: zod.union([
      zod
        .string()
        .max(filterControllerFindOneResponseActionContentWarningOneMax),
      zod.null(),
    ]),
    type: zod.enum(['blur', 'markRead', 'hide']),
  }),
  conditions: zod.object({
    authors: zod.array(zod.string()).optional(),
    categories: zod.array(zod.string()).optional(),
    contentContains: zod.array(zod.string()).optional(),
    feeds: zod.array(zod.string()).optional(),
    keywords: zod.array(zod.string()).optional(),
    titleContains: zod.array(zod.string()).optional(),
  }),
  description: zod
    .string()
    .max(filterControllerFindOneResponseDescriptionMax)
    .optional(),
  id: zod.uuid().stringFormat('uuid', filterControllerFindOneResponseIdRegExp),
  isActive: zod
    .boolean()
    .default(filterControllerFindOneResponseIsActiveDefault),
  name: zod.union([
    zod.string().max(filterControllerFindOneResponseNameOneMax),
    zod.null(),
  ]),
});

export const FilterControllerUpdateParams = zod.object({
  id: zod.string(),
});

export const filterControllerUpdateBodyNameMax = 255;

export const filterControllerUpdateBodyDescriptionMax = 1024;

export const filterControllerUpdateBodyIsActiveDefault = true;
export const filterControllerUpdateBodyActionContentWarningOneMax = 512;

export const FilterControllerUpdateBody = zod.object({
  action: zod.object({
    contentWarning: zod
      .union([
        zod.string().max(filterControllerUpdateBodyActionContentWarningOneMax),
        zod.null(),
      ])
      .optional(),
    type: zod.enum(['blur', 'markRead', 'hide']).optional(),
  }),
  conditions: zod.object({
    authors: zod.array(zod.string()).optional(),
    categories: zod.array(zod.string()).optional(),
    contentContains: zod.array(zod.string()).optional(),
    feeds: zod.array(zod.string()).optional(),
    keywords: zod.array(zod.string()).optional(),
    titleContains: zod.array(zod.string()).optional(),
  }),
  description: zod
    .string()
    .max(filterControllerUpdateBodyDescriptionMax)
    .optional(),
  isActive: zod.boolean().default(filterControllerUpdateBodyIsActiveDefault),
  name: zod.string().min(1).max(filterControllerUpdateBodyNameMax).optional(),
});

export const filterControllerUpdateResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const filterControllerUpdateResponseNameOneMax = 255;

export const filterControllerUpdateResponseDescriptionMax = 1024;

export const filterControllerUpdateResponseIsActiveDefault = true;
export const filterControllerUpdateResponseActionContentWarningOneMax = 512;

export const FilterControllerUpdateResponse = zod.object({
  action: zod.object({
    contentWarning: zod.union([
      zod
        .string()
        .max(filterControllerUpdateResponseActionContentWarningOneMax),
      zod.null(),
    ]),
    type: zod.enum(['blur', 'markRead', 'hide']),
  }),
  conditions: zod.object({
    authors: zod.array(zod.string()).optional(),
    categories: zod.array(zod.string()).optional(),
    contentContains: zod.array(zod.string()).optional(),
    feeds: zod.array(zod.string()).optional(),
    keywords: zod.array(zod.string()).optional(),
    titleContains: zod.array(zod.string()).optional(),
  }),
  description: zod
    .string()
    .max(filterControllerUpdateResponseDescriptionMax)
    .optional(),
  id: zod.uuid().stringFormat('uuid', filterControllerUpdateResponseIdRegExp),
  isActive: zod
    .boolean()
    .default(filterControllerUpdateResponseIsActiveDefault),
  name: zod.union([
    zod.string().max(filterControllerUpdateResponseNameOneMax),
    zod.null(),
  ]),
});

export const FilterControllerRemoveParams = zod.object({
  id: zod.string(),
});
