/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const feedControllerCreateBodyFolderNameOneMin = 2;

export const FeedControllerCreateBody = zod.object({
  description: zod.string().optional(),
  folderName: zod.union([
    zod.string().min(feedControllerCreateBodyFolderNameOneMin),
    zod.null(),
  ]),
  url: zod.url().min(1),
});

export const feedControllerFindAllResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const feedControllerFindAllResponseEtagHeaderDefault = ``;
export const feedControllerFindAllResponseParsingErrorCountDefault = 0;
export const feedControllerFindAllResponseParsingErrorCountMin = 0;

export const feedControllerFindAllResponseAuthorsItemEmailRegExp =
  /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9-]*\.)+[A-Za-z]{2,}$/;
export const feedControllerFindAllResponseAuthorsDefault = [];
export const feedControllerFindAllResponseContributorsItemEmailRegExp =
  /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9-]*\.)+[A-Za-z]{2,}$/;
export const feedControllerFindAllResponseContributorsDefault = [];
export const feedControllerFindAllResponseCategoriesDefault = [];
export const feedControllerFindAllResponseImageOneWidthMin = 0;

export const feedControllerFindAllResponseImageOneHeightMin = 0;

export const feedControllerFindAllResponseLastCheckedRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindAllResponseUpdatedOneRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindAllResponsePodcastOneTrailersItemLengthMin = 0;

export const feedControllerFindAllResponsePodcastOneValueSuggestedMin = 0;

export const feedControllerFindAllResponsePodcastOneValueValueRecipientsItemSplitMin = 0;

export const feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemStartTimeMin = 0;

export const feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemDurationMin = 0;

export const feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemRemoteStartTimeMin = 0;

export const feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemRemotePercentageMin = 0;

export const feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemValueRecipientsItemSplitMin = 0;

export const feedControllerFindAllResponsePodcastOneLiveItemsItemStartRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindAllResponsePodcastOneLiveItemsItemEndRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindAllResponseUnreadCountOneMin = 0;

export const feedControllerFindAllResponseFolderIdOneRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FeedControllerFindAllResponseItem = zod.object({
  authors: zod
    .array(
      zod.object({
        email: zod
          .email()
          .stringFormat(
            'email',
            feedControllerFindAllResponseAuthorsItemEmailRegExp,
          )
          .optional(),
        name: zod.string(),
        uri: zod.url().optional(),
      }),
    )
    .default(feedControllerFindAllResponseAuthorsDefault),
  categories: zod
    .array(
      zod.object({
        label: zod.string().optional(),
        scheme: zod.string().optional(),
        term: zod.string().optional(),
      }),
    )
    .default(feedControllerFindAllResponseCategoriesDefault),
  contributors: zod
    .array(
      zod.object({
        email: zod
          .email()
          .stringFormat(
            'email',
            feedControllerFindAllResponseContributorsItemEmailRegExp,
          )
          .optional(),
        name: zod.string(),
        uri: zod.url().optional(),
      }),
    )
    .default(feedControllerFindAllResponseContributorsDefault),
  copyright: zod.union([zod.string(), zod.null()]),
  crawler: zod.union([zod.boolean(), zod.null()]),
  etag_header: zod
    .string()
    .default(feedControllerFindAllResponseEtagHeaderDefault),
  explicit: zod.union([zod.boolean(), zod.null()]),
  favicon: zod.union([zod.url(), zod.null()]),
  folderId: zod.union([
    zod
      .uuid()
      .stringFormat('uuid', feedControllerFindAllResponseFolderIdOneRegExp),
    zod.null(),
  ]),
  geo: zod.union([
    zod.object({
      box: zod
        .object({
          lowerCorner: zod.object({
            lat: zod.number(),
            lng: zod.number(),
          }),
          upperCorner: zod.object({
            lat: zod.number(),
            lng: zod.number(),
          }),
        })
        .optional(),
      elev: zod.number().optional(),
      featureName: zod.string().optional(),
      featureTypeTag: zod.string().optional(),
      floor: zod.number().optional(),
      line: zod
        .object({
          points: zod.array(
            zod.object({
              lat: zod.number(),
              lng: zod.number(),
            }),
          ),
        })
        .optional(),
      point: zod
        .object({
          lat: zod.number(),
          lng: zod.number(),
        })
        .optional(),
      polygon: zod
        .object({
          points: zod.array(
            zod.object({
              lat: zod.number(),
              lng: zod.number(),
            }),
          ),
        })
        .optional(),
      radius: zod.number().optional(),
      relationshipTag: zod.string().optional(),
    }),
    zod.null(),
  ]),
  id: zod.uuid().stringFormat('uuid', feedControllerFindAllResponseIdRegExp),
  image: zod.union([
    zod.object({
      description: zod.string().optional(),
      height: zod
        .number()
        .min(feedControllerFindAllResponseImageOneHeightMin)
        .optional(),
      link: zod.url(),
      title: zod.string().optional(),
      url: zod.url(),
      width: zod
        .number()
        .min(feedControllerFindAllResponseImageOneWidthMin)
        .optional(),
    }),
    zod.null(),
  ]),
  last_modified_header: zod.union([zod.string(), zod.null()]),
  lastChecked: zod.iso
    .datetime({})
    .stringFormat('date-time', feedControllerFindAllResponseLastCheckedRegExp),
  parsingErrorCount: zod
    .number()
    .min(feedControllerFindAllResponseParsingErrorCountMin)
    .default(feedControllerFindAllResponseParsingErrorCountDefault),
  parsingErrorMessage: zod.union([zod.string(), zod.null()]),
  podcast: zod.union([
    zod.object({
      blocks: zod
        .array(
          zod.object({
            id: zod.string().optional(),
            value: zod.boolean(),
          }),
        )
        .optional(),
      fundings: zod
        .array(
          zod.object({
            display: zod.string().optional(),
            url: zod.url(),
          }),
        )
        .optional(),
      guid: zod.string().optional(),
      images: zod
        .object({
          srcset: zod.string().optional(),
        })
        .optional(),
      liveItems: zod
        .array(
          zod.object({
            contentLinks: zod
              .array(
                zod.object({
                  display: zod.string().optional(),
                  href: zod.url(),
                }),
              )
              .optional(),
            end: zod.iso
              .datetime({})
              .stringFormat(
                'date-time',
                feedControllerFindAllResponsePodcastOneLiveItemsItemEndRegExp,
              )
              .optional(),
            start: zod.iso
              .datetime({})
              .stringFormat(
                'date-time',
                feedControllerFindAllResponsePodcastOneLiveItemsItemStartRegExp,
              ),
            status: zod.string(),
          }),
        )
        .optional(),
      location: zod
        .object({
          display: zod.string(),
          geo: zod.string().optional(),
          osm: zod.string().optional(),
        })
        .optional(),
      locked: zod
        .object({
          owner: zod.string().optional(),
          value: zod.boolean(),
        })
        .optional(),
      medium: zod.string().optional(),
      persons: zod
        .array(
          zod.object({
            display: zod.string(),
            group: zod.string().optional(),
            href: zod.url().optional(),
            img: zod.url().optional(),
            role: zod.string().optional(),
          }),
        )
        .optional(),
      podping: zod
        .object({
          usesPodping: zod.boolean().optional(),
        })
        .optional(),
      podroll: zod
        .object({
          remoteItems: zod
            .array(
              zod.object({
                feedGuid: zod.string(),
                feedUrl: zod.url().optional(),
                itemGuid: zod.string().optional(),
                medium: zod.string().optional(),
              }),
            )
            .optional(),
        })
        .optional(),
      remoteItems: zod
        .array(
          zod.object({
            feedGuid: zod.string(),
            feedUrl: zod.url().optional(),
            itemGuid: zod.string().optional(),
            medium: zod.string().optional(),
          }),
        )
        .optional(),
      trailers: zod
        .array(
          zod.object({
            display: zod.string(),
            length: zod
              .number()
              .min(feedControllerFindAllResponsePodcastOneTrailersItemLengthMin)
              .optional(),
            pubDate: zod.string(),
            season: zod.number().optional(),
            type: zod.string().optional(),
            url: zod.url(),
          }),
        )
        .optional(),
      txts: zod
        .array(
          zod.object({
            display: zod.string(),
            purpose: zod.string().optional(),
          }),
        )
        .optional(),
      updateFrequency: zod
        .object({
          complete: zod.boolean().optional(),
          display: zod.string(),
          dtstart: zod.string().optional(),
          rrule: zod.string().optional(),
        })
        .optional(),
      value: zod
        .object({
          method: zod.string(),
          suggested: zod
            .number()
            .min(feedControllerFindAllResponsePodcastOneValueSuggestedMin)
            .optional(),
          type: zod.string(),
          valueRecipients: zod
            .array(
              zod.object({
                address: zod.string(),
                customKey: zod.string().optional(),
                customValue: zod.string().optional(),
                fee: zod.boolean().optional(),
                name: zod.string().optional(),
                split: zod
                  .number()
                  .min(
                    feedControllerFindAllResponsePodcastOneValueValueRecipientsItemSplitMin,
                  ),
                type: zod.string(),
              }),
            )
            .optional(),
          valueTimeSplits: zod
            .array(
              zod.object({
                duration: zod
                  .number()
                  .min(
                    feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemDurationMin,
                  ),
                remoteItem: zod
                  .object({
                    feedGuid: zod.string(),
                    feedUrl: zod.url().optional(),
                    itemGuid: zod.string().optional(),
                    medium: zod.string().optional(),
                  })
                  .optional(),
                remotePercentage: zod
                  .number()
                  .min(
                    feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemRemotePercentageMin,
                  )
                  .optional(),
                remoteStartTime: zod
                  .number()
                  .min(
                    feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemRemoteStartTimeMin,
                  )
                  .optional(),
                startTime: zod
                  .number()
                  .min(
                    feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemStartTimeMin,
                  ),
                valueRecipients: zod
                  .array(
                    zod.object({
                      address: zod.string(),
                      customKey: zod.string().optional(),
                      customValue: zod.string().optional(),
                      fee: zod.boolean().optional(),
                      name: zod.string().optional(),
                      split: zod
                        .number()
                        .min(
                          feedControllerFindAllResponsePodcastOneValueValueTimeSplitsItemValueRecipientsItemSplitMin,
                        ),
                      type: zod.string(),
                    }),
                  )
                  .optional(),
              }),
            )
            .optional(),
        })
        .optional(),
    }),
    zod.null(),
  ]),
  publisher: zod.union([zod.string(), zod.null()]),
  rights: zod.union([zod.string(), zod.null()]),
  site_url: zod.union([zod.url(), zod.null()]),
  subject: zod.union([zod.string(), zod.null()]),
  subtitle: zod.union([zod.string(), zod.null()]),
  title: zod.string(),
  unreadCount: zod.union([
    zod.number().min(feedControllerFindAllResponseUnreadCountOneMin),
    zod.null(),
  ]),
  updateBase: zod.union([zod.string(), zod.null()]),
  updated: zod.union([
    zod.iso
      .datetime({})
      .stringFormat('date-time', feedControllerFindAllResponseUpdatedOneRegExp),
    zod.null(),
  ]),
  updateFrequency: zod.union([zod.number(), zod.null()]),
  updatePeriod: zod.union([zod.string(), zod.null()]),
  url: zod.url(),
  userAgent: zod.union([zod.string(), zod.null()]),
  youtube: zod.union([
    zod.object({
      channelId: zod.string().optional(),
      playlistId: zod.string().optional(),
    }),
    zod.null(),
  ]),
});
export const FeedControllerFindAllResponse = zod.array(
  FeedControllerFindAllResponseItem,
);

export const feedControllerDiscoverBodyUrlMax = 2048;

export const feedControllerDiscoverBodyUsernameMax = 255;

export const feedControllerDiscoverBodyPasswordMax = 255;

export const feedControllerDiscoverBodyUserAgentMax = 255;

export const FeedControllerDiscoverBody = zod.object({
  password: zod
    .string()
    .min(1)
    .max(feedControllerDiscoverBodyPasswordMax)
    .optional(),
  url: zod.string().min(1).max(feedControllerDiscoverBodyUrlMax),
  user_agent: zod
    .string()
    .min(1)
    .max(feedControllerDiscoverBodyUserAgentMax)
    .optional(),
  username: zod
    .string()
    .min(1)
    .max(feedControllerDiscoverBodyUsernameMax)
    .optional(),
});

export const feedControllerDiscoverResponseTitleOneMax = 255;

export const feedControllerDiscoverResponseUrlMax = 2048;

export const FeedControllerDiscoverResponseItem = zod.object({
  format: zod.string(),
  title: zod.union([
    zod.string().min(1).max(feedControllerDiscoverResponseTitleOneMax),
    zod.null(),
  ]),
  url: zod.url().min(1).max(feedControllerDiscoverResponseUrlMax),
});
export const FeedControllerDiscoverResponse = zod.array(
  FeedControllerDiscoverResponseItem,
);

export const FeedControllerImportBody = zod.object({
  file: zod.looseObject({}).describe('OPML file to import'),
});

export const FeedControllerMarkAllReadParams = zod.object({
  id: zod.string(),
});

export const FeedControllerFindOneParams = zod.object({
  id: zod.string(),
});

export const feedControllerFindOneResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const feedControllerFindOneResponseEtagHeaderDefault = ``;
export const feedControllerFindOneResponseParsingErrorCountDefault = 0;
export const feedControllerFindOneResponseParsingErrorCountMin = 0;

export const feedControllerFindOneResponseAuthorsItemEmailRegExp =
  /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9-]*\.)+[A-Za-z]{2,}$/;
export const feedControllerFindOneResponseAuthorsDefault = [];
export const feedControllerFindOneResponseContributorsItemEmailRegExp =
  /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9-]*\.)+[A-Za-z]{2,}$/;
export const feedControllerFindOneResponseContributorsDefault = [];
export const feedControllerFindOneResponseCategoriesDefault = [];
export const feedControllerFindOneResponseImageOneWidthMin = 0;

export const feedControllerFindOneResponseImageOneHeightMin = 0;

export const feedControllerFindOneResponseLastCheckedRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindOneResponseUpdatedOneRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindOneResponsePodcastOneTrailersItemLengthMin = 0;

export const feedControllerFindOneResponsePodcastOneValueSuggestedMin = 0;

export const feedControllerFindOneResponsePodcastOneValueValueRecipientsItemSplitMin = 0;

export const feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemStartTimeMin = 0;

export const feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemDurationMin = 0;

export const feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemRemoteStartTimeMin = 0;

export const feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemRemotePercentageMin = 0;

export const feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemValueRecipientsItemSplitMin = 0;

export const feedControllerFindOneResponsePodcastOneLiveItemsItemStartRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindOneResponsePodcastOneLiveItemsItemEndRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const feedControllerFindOneResponseUnreadCountOneMin = 0;

export const feedControllerFindOneResponseFolderIdOneRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FeedControllerFindOneResponse = zod.object({
  authors: zod
    .array(
      zod.object({
        email: zod
          .email()
          .stringFormat(
            'email',
            feedControllerFindOneResponseAuthorsItemEmailRegExp,
          )
          .optional(),
        name: zod.string(),
        uri: zod.url().optional(),
      }),
    )
    .default(feedControllerFindOneResponseAuthorsDefault),
  categories: zod
    .array(
      zod.object({
        label: zod.string().optional(),
        scheme: zod.string().optional(),
        term: zod.string().optional(),
      }),
    )
    .default(feedControllerFindOneResponseCategoriesDefault),
  contributors: zod
    .array(
      zod.object({
        email: zod
          .email()
          .stringFormat(
            'email',
            feedControllerFindOneResponseContributorsItemEmailRegExp,
          )
          .optional(),
        name: zod.string(),
        uri: zod.url().optional(),
      }),
    )
    .default(feedControllerFindOneResponseContributorsDefault),
  copyright: zod.union([zod.string(), zod.null()]),
  crawler: zod.union([zod.boolean(), zod.null()]),
  etag_header: zod
    .string()
    .default(feedControllerFindOneResponseEtagHeaderDefault),
  explicit: zod.union([zod.boolean(), zod.null()]),
  favicon: zod.union([zod.url(), zod.null()]),
  folderId: zod.union([
    zod
      .uuid()
      .stringFormat('uuid', feedControllerFindOneResponseFolderIdOneRegExp),
    zod.null(),
  ]),
  geo: zod.union([
    zod.object({
      box: zod
        .object({
          lowerCorner: zod.object({
            lat: zod.number(),
            lng: zod.number(),
          }),
          upperCorner: zod.object({
            lat: zod.number(),
            lng: zod.number(),
          }),
        })
        .optional(),
      elev: zod.number().optional(),
      featureName: zod.string().optional(),
      featureTypeTag: zod.string().optional(),
      floor: zod.number().optional(),
      line: zod
        .object({
          points: zod.array(
            zod.object({
              lat: zod.number(),
              lng: zod.number(),
            }),
          ),
        })
        .optional(),
      point: zod
        .object({
          lat: zod.number(),
          lng: zod.number(),
        })
        .optional(),
      polygon: zod
        .object({
          points: zod.array(
            zod.object({
              lat: zod.number(),
              lng: zod.number(),
            }),
          ),
        })
        .optional(),
      radius: zod.number().optional(),
      relationshipTag: zod.string().optional(),
    }),
    zod.null(),
  ]),
  id: zod.uuid().stringFormat('uuid', feedControllerFindOneResponseIdRegExp),
  image: zod.union([
    zod.object({
      description: zod.string().optional(),
      height: zod
        .number()
        .min(feedControllerFindOneResponseImageOneHeightMin)
        .optional(),
      link: zod.url(),
      title: zod.string().optional(),
      url: zod.url(),
      width: zod
        .number()
        .min(feedControllerFindOneResponseImageOneWidthMin)
        .optional(),
    }),
    zod.null(),
  ]),
  last_modified_header: zod.union([zod.string(), zod.null()]),
  lastChecked: zod.iso
    .datetime({})
    .stringFormat('date-time', feedControllerFindOneResponseLastCheckedRegExp),
  parsingErrorCount: zod
    .number()
    .min(feedControllerFindOneResponseParsingErrorCountMin)
    .default(feedControllerFindOneResponseParsingErrorCountDefault),
  parsingErrorMessage: zod.union([zod.string(), zod.null()]),
  podcast: zod.union([
    zod.object({
      blocks: zod
        .array(
          zod.object({
            id: zod.string().optional(),
            value: zod.boolean(),
          }),
        )
        .optional(),
      fundings: zod
        .array(
          zod.object({
            display: zod.string().optional(),
            url: zod.url(),
          }),
        )
        .optional(),
      guid: zod.string().optional(),
      images: zod
        .object({
          srcset: zod.string().optional(),
        })
        .optional(),
      liveItems: zod
        .array(
          zod.object({
            contentLinks: zod
              .array(
                zod.object({
                  display: zod.string().optional(),
                  href: zod.url(),
                }),
              )
              .optional(),
            end: zod.iso
              .datetime({})
              .stringFormat(
                'date-time',
                feedControllerFindOneResponsePodcastOneLiveItemsItemEndRegExp,
              )
              .optional(),
            start: zod.iso
              .datetime({})
              .stringFormat(
                'date-time',
                feedControllerFindOneResponsePodcastOneLiveItemsItemStartRegExp,
              ),
            status: zod.string(),
          }),
        )
        .optional(),
      location: zod
        .object({
          display: zod.string(),
          geo: zod.string().optional(),
          osm: zod.string().optional(),
        })
        .optional(),
      locked: zod
        .object({
          owner: zod.string().optional(),
          value: zod.boolean(),
        })
        .optional(),
      medium: zod.string().optional(),
      persons: zod
        .array(
          zod.object({
            display: zod.string(),
            group: zod.string().optional(),
            href: zod.url().optional(),
            img: zod.url().optional(),
            role: zod.string().optional(),
          }),
        )
        .optional(),
      podping: zod
        .object({
          usesPodping: zod.boolean().optional(),
        })
        .optional(),
      podroll: zod
        .object({
          remoteItems: zod
            .array(
              zod.object({
                feedGuid: zod.string(),
                feedUrl: zod.url().optional(),
                itemGuid: zod.string().optional(),
                medium: zod.string().optional(),
              }),
            )
            .optional(),
        })
        .optional(),
      remoteItems: zod
        .array(
          zod.object({
            feedGuid: zod.string(),
            feedUrl: zod.url().optional(),
            itemGuid: zod.string().optional(),
            medium: zod.string().optional(),
          }),
        )
        .optional(),
      trailers: zod
        .array(
          zod.object({
            display: zod.string(),
            length: zod
              .number()
              .min(feedControllerFindOneResponsePodcastOneTrailersItemLengthMin)
              .optional(),
            pubDate: zod.string(),
            season: zod.number().optional(),
            type: zod.string().optional(),
            url: zod.url(),
          }),
        )
        .optional(),
      txts: zod
        .array(
          zod.object({
            display: zod.string(),
            purpose: zod.string().optional(),
          }),
        )
        .optional(),
      updateFrequency: zod
        .object({
          complete: zod.boolean().optional(),
          display: zod.string(),
          dtstart: zod.string().optional(),
          rrule: zod.string().optional(),
        })
        .optional(),
      value: zod
        .object({
          method: zod.string(),
          suggested: zod
            .number()
            .min(feedControllerFindOneResponsePodcastOneValueSuggestedMin)
            .optional(),
          type: zod.string(),
          valueRecipients: zod
            .array(
              zod.object({
                address: zod.string(),
                customKey: zod.string().optional(),
                customValue: zod.string().optional(),
                fee: zod.boolean().optional(),
                name: zod.string().optional(),
                split: zod
                  .number()
                  .min(
                    feedControllerFindOneResponsePodcastOneValueValueRecipientsItemSplitMin,
                  ),
                type: zod.string(),
              }),
            )
            .optional(),
          valueTimeSplits: zod
            .array(
              zod.object({
                duration: zod
                  .number()
                  .min(
                    feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemDurationMin,
                  ),
                remoteItem: zod
                  .object({
                    feedGuid: zod.string(),
                    feedUrl: zod.url().optional(),
                    itemGuid: zod.string().optional(),
                    medium: zod.string().optional(),
                  })
                  .optional(),
                remotePercentage: zod
                  .number()
                  .min(
                    feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemRemotePercentageMin,
                  )
                  .optional(),
                remoteStartTime: zod
                  .number()
                  .min(
                    feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemRemoteStartTimeMin,
                  )
                  .optional(),
                startTime: zod
                  .number()
                  .min(
                    feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemStartTimeMin,
                  ),
                valueRecipients: zod
                  .array(
                    zod.object({
                      address: zod.string(),
                      customKey: zod.string().optional(),
                      customValue: zod.string().optional(),
                      fee: zod.boolean().optional(),
                      name: zod.string().optional(),
                      split: zod
                        .number()
                        .min(
                          feedControllerFindOneResponsePodcastOneValueValueTimeSplitsItemValueRecipientsItemSplitMin,
                        ),
                      type: zod.string(),
                    }),
                  )
                  .optional(),
              }),
            )
            .optional(),
        })
        .optional(),
    }),
    zod.null(),
  ]),
  publisher: zod.union([zod.string(), zod.null()]),
  rights: zod.union([zod.string(), zod.null()]),
  site_url: zod.union([zod.url(), zod.null()]),
  subject: zod.union([zod.string(), zod.null()]),
  subtitle: zod.union([zod.string(), zod.null()]),
  title: zod.string(),
  unreadCount: zod.union([
    zod.number().min(feedControllerFindOneResponseUnreadCountOneMin),
    zod.null(),
  ]),
  updateBase: zod.union([zod.string(), zod.null()]),
  updated: zod.union([
    zod.iso
      .datetime({})
      .stringFormat('date-time', feedControllerFindOneResponseUpdatedOneRegExp),
    zod.null(),
  ]),
  updateFrequency: zod.union([zod.number(), zod.null()]),
  updatePeriod: zod.union([zod.string(), zod.null()]),
  url: zod.url(),
  userAgent: zod.union([zod.string(), zod.null()]),
  youtube: zod.union([
    zod.object({
      channelId: zod.string().optional(),
      playlistId: zod.string().optional(),
    }),
    zod.null(),
  ]),
});

export const FeedControllerRemoveParams = zod.object({
  id: zod.string(),
});

export const FeedControllerUpdateParams = zod.object({
  id: zod.string(),
});

export const feedControllerUpdateBodyDescriptionMin = 0;
export const feedControllerUpdateBodyDescriptionMax = 1000;

export const feedControllerUpdateBodyFolderIdOneRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FeedControllerUpdateBody = zod.object({
  description: zod
    .string()
    .min(feedControllerUpdateBodyDescriptionMin)
    .max(feedControllerUpdateBodyDescriptionMax)
    .optional(),
  folderId: zod.union([
    zod.uuid().stringFormat('uuid', feedControllerUpdateBodyFolderIdOneRegExp),
    zod.null(),
  ]),
});

export const feedControllerUpdateResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const feedControllerUpdateResponseFeedIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const feedControllerUpdateResponseFolderIdOneRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FeedControllerUpdateResponse = zod.object({
  description: zod.union([zod.string(), zod.null()]),
  feedId: zod
    .uuid()
    .stringFormat('uuid', feedControllerUpdateResponseFeedIdRegExp),
  folderId: zod.union([
    zod
      .uuid()
      .stringFormat('uuid', feedControllerUpdateResponseFolderIdOneRegExp),
    zod.null(),
  ]),
  id: zod.uuid().stringFormat('uuid', feedControllerUpdateResponseIdRegExp),
  userId: zod.string(),
});
