/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

import type { RequestHandlerOptions } from 'msw';
import { HttpResponse, http } from 'msw';

export const getAppControllerGetProfileMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/me',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getAppControllerGetLoginMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/callback',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getAppMock = () => [
  getAppControllerGetProfileMockHandler(),
  getAppControllerGetLoginMockHandler(),
];
