/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useQuery } from '@tanstack/react-query';

export type appControllerGetProfileResponse200 = {
  data: void;
  status: 200;
};

export type appControllerGetProfileResponse401 = {
  data: void;
  status: 401;
};

export type appControllerGetProfileResponse500 = {
  data: void;
  status: 500;
};

export type appControllerGetProfileResponseSuccess =
  appControllerGetProfileResponse200 & {
    headers: Headers;
  };
export type appControllerGetProfileResponseError = (
  | appControllerGetProfileResponse401
  | appControllerGetProfileResponse500
) & {
  headers: Headers;
};

export type appControllerGetProfileResponse =
  | appControllerGetProfileResponseSuccess
  | appControllerGetProfileResponseError;

export const getAppControllerGetProfileUrl = () => {
  return `/me`;
};

export const appControllerGetProfile = async (
  options?: RequestInit,
): Promise<appControllerGetProfileResponse> => {
  const res = await fetch(getAppControllerGetProfileUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetProfileResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as appControllerGetProfileResponse;
};

export const getAppControllerGetProfileQueryKey = () => {
  return [`/me`] as const;
};

export const getAppControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetProfile>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof appControllerGetProfile>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAppControllerGetProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerGetProfile>>
  > = ({ signal }) => appControllerGetProfile({ signal, ...fetchOptions });

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetProfile>>
>;
export type AppControllerGetProfileQueryError = void;

export function useAppControllerGetProfile<
  TData = Awaited<ReturnType<typeof appControllerGetProfile>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetProfile>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetProfile<
  TData = Awaited<ReturnType<typeof appControllerGetProfile>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetProfile>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetProfile<
  TData = Awaited<ReturnType<typeof appControllerGetProfile>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetProfile>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAppControllerGetProfile<
  TData = Awaited<ReturnType<typeof appControllerGetProfile>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetProfile>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAppControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type appControllerGetLoginResponse200 = {
  data: void;
  status: 200;
};

export type appControllerGetLoginResponse401 = {
  data: void;
  status: 401;
};

export type appControllerGetLoginResponse500 = {
  data: void;
  status: 500;
};

export type appControllerGetLoginResponseSuccess =
  appControllerGetLoginResponse200 & {
    headers: Headers;
  };
export type appControllerGetLoginResponseError = (
  | appControllerGetLoginResponse401
  | appControllerGetLoginResponse500
) & {
  headers: Headers;
};

export type appControllerGetLoginResponse =
  | appControllerGetLoginResponseSuccess
  | appControllerGetLoginResponseError;

export const getAppControllerGetLoginUrl = () => {
  return `/callback`;
};

export const appControllerGetLogin = async (
  options?: RequestInit,
): Promise<appControllerGetLoginResponse> => {
  const res = await fetch(getAppControllerGetLoginUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetLoginResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as appControllerGetLoginResponse;
};

export const getAppControllerGetLoginQueryKey = () => {
  return [`/callback`] as const;
};

export const getAppControllerGetLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetLogin>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof appControllerGetLogin>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetLoginQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerGetLogin>>
  > = ({ signal }) => appControllerGetLogin({ signal, ...fetchOptions });

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetLogin>>
>;
export type AppControllerGetLoginQueryError = void;

export function useAppControllerGetLogin<
  TData = Awaited<ReturnType<typeof appControllerGetLogin>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetLogin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetLogin>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetLogin>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetLogin<
  TData = Awaited<ReturnType<typeof appControllerGetLogin>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetLogin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetLogin>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetLogin>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetLogin<
  TData = Awaited<ReturnType<typeof appControllerGetLogin>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetLogin>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAppControllerGetLogin<
  TData = Awaited<ReturnType<typeof appControllerGetLogin>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetLogin>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAppControllerGetLoginQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
