services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: lion
    volumes:
      - db:/data/postgres
    ports:
      - "5423:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  valkey:
    container_name: valkey
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    environment:
      VALKEY_EXTRA_FLAGS: "--appendonly yes"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - valkey:/data

volumes:
  db:
  valkey:
