packages:
  - lionsmane
  - lionsmane-fe

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - msgpackr-extract
  - msw
  - unrs-resolver
