packages:
  - lionsmane
  - lionsmane-fe
  - lionsmane-common

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@suites/di.nestjs'
  - '@suites/doubles.vitest'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - keccak
  - msgpackr-extract
  - msw
  - scrypt
  - secp256k1
  - sha3
  - unrs-resolver
  - websocket
