#
# Copyright (c) 2025 Margaret Miller.  Licensed under the EUPL-1.2-or-later.
#
quarkus.keycloak.devservices.port=8675
%dev.quarkus.datasource.dev-ui.allow-sql=true
quarkus.keycloak.devservices.realm-path=realm-export.json