#
# Copyright (c) 2025 Margaret Miller.  Licensed under the EUPL-1.2-or-later.
#
quarkus.keycloak.devservices.port=8675
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=pipinalsolovesC0ausingPr0blemsanditsfunny
API_URL=http://127.0.0.1:8080
