/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { HttpResponse, http } from 'msw';

import type { HealthControllerCheck200 } from '../model';

export const getHealthControllerCheckResponseMock = (
  overrideResponse: Partial<Extract<HealthControllerCheck200, object>> = {},
): HealthControllerCheck200 => ({
  details: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: {
        status: faker.string.alpha({ length: { max: 20, min: 10 } }),
      },
    },
    undefined,
  ]),
  error: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: {
        status: faker.string.alpha({ length: { max: 20, min: 10 } }),
      },
    },
    null,
  ]),
  info: faker.helpers.arrayElement([
    {
      [faker.string.alphanumeric(5)]: {
        status: faker.string.alpha({ length: { max: 20, min: 10 } }),
      },
    },
    null,
  ]),
  status: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getHealthControllerCheckMockHandler = (
  overrideResponse?:
    | HealthControllerCheck200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<HealthControllerCheck200> | HealthControllerCheck200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/health',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getHealthControllerCheckResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getHealthMock = () => [getHealthControllerCheckMockHandler()];
