/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as DashboardArticleIdRouteImport } from './routes/dashboard/$articleId';
import { Route as DashboardFeedFeedIdRouteImport } from './routes/dashboard/feed.$feedId';
import { Route as DashboardFilterFilterIdRouteImport } from './routes/dashboard/filter.$filterId';
import { Route as DashboardFilterIndexRouteImport } from './routes/dashboard/filter.index';
import { Route as DashboardFilterNewRouteImport } from './routes/dashboard/filter.new';
import { Route as DashboardFolderFolderIdRouteImport } from './routes/dashboard/folder.$folderId';
import { Route as DashboardHiddenRouteImport } from './routes/dashboard/hidden';
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index';
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route';
import { Route as DashboardSearchRouteImport } from './routes/dashboard/search';
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings';
import { Route as IndexRouteImport } from './routes/index';
import { Route as LoginRouteImport } from './routes/login';
import { Route as SignupRouteImport } from './routes/signup';

const SignupRoute = SignupRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: '/signup',
  path: '/signup',
} as any);
const LoginRoute = LoginRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: '/login',
  path: '/login',
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: '/dashboard',
  path: '/dashboard',
} as any);
const IndexRoute = IndexRouteImport.update({
  getParentRoute: () => rootRouteImport,
  id: '/',
  path: '/',
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/',
  path: '/',
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/settings',
  path: '/settings',
} as any);
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/search',
  path: '/search',
} as any);
const DashboardHiddenRoute = DashboardHiddenRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/hidden',
  path: '/hidden',
} as any);
const DashboardArticleIdRoute = DashboardArticleIdRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/$articleId',
  path: '/$articleId',
} as any);
const DashboardFilterIndexRoute = DashboardFilterIndexRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/filter/',
  path: '/filter/',
} as any);
const DashboardFolderFolderIdRoute = DashboardFolderFolderIdRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/folder/$folderId',
  path: '/folder/$folderId',
} as any);
const DashboardFilterNewRoute = DashboardFilterNewRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/filter/new',
  path: '/filter/new',
} as any);
const DashboardFilterFilterIdRoute = DashboardFilterFilterIdRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/filter/$filterId',
  path: '/filter/$filterId',
} as any);
const DashboardFeedFeedIdRoute = DashboardFeedFeedIdRouteImport.update({
  getParentRoute: () => DashboardRouteRoute,
  id: '/feed/$feedId',
  path: '/feed/$feedId',
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/dashboard/$articleId': typeof DashboardArticleIdRoute;
  '/dashboard/hidden': typeof DashboardHiddenRoute;
  '/dashboard/search': typeof DashboardSearchRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/dashboard/feed/$feedId': typeof DashboardFeedFeedIdRoute;
  '/dashboard/filter/$filterId': typeof DashboardFilterFilterIdRoute;
  '/dashboard/filter/new': typeof DashboardFilterNewRoute;
  '/dashboard/folder/$folderId': typeof DashboardFolderFolderIdRoute;
  '/dashboard/filter': typeof DashboardFilterIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/dashboard/$articleId': typeof DashboardArticleIdRoute;
  '/dashboard/hidden': typeof DashboardHiddenRoute;
  '/dashboard/search': typeof DashboardSearchRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/dashboard/feed/$feedId': typeof DashboardFeedFeedIdRoute;
  '/dashboard/filter/$filterId': typeof DashboardFilterFilterIdRoute;
  '/dashboard/filter/new': typeof DashboardFilterNewRoute;
  '/dashboard/folder/$folderId': typeof DashboardFolderFolderIdRoute;
  '/dashboard/filter': typeof DashboardFilterIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/dashboard': typeof DashboardRouteRouteWithChildren;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/dashboard/$articleId': typeof DashboardArticleIdRoute;
  '/dashboard/hidden': typeof DashboardHiddenRoute;
  '/dashboard/search': typeof DashboardSearchRoute;
  '/dashboard/settings': typeof DashboardSettingsRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/dashboard/feed/$feedId': typeof DashboardFeedFeedIdRoute;
  '/dashboard/filter/$filterId': typeof DashboardFilterFilterIdRoute;
  '/dashboard/filter/new': typeof DashboardFilterNewRoute;
  '/dashboard/folder/$folderId': typeof DashboardFolderFolderIdRoute;
  '/dashboard/filter/': typeof DashboardFilterIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/$articleId'
    | '/dashboard/hidden'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/feed/$feedId'
    | '/dashboard/filter/$filterId'
    | '/dashboard/filter/new'
    | '/dashboard/folder/$folderId'
    | '/dashboard/filter';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/$articleId'
    | '/dashboard/hidden'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/feed/$feedId'
    | '/dashboard/filter/$filterId'
    | '/dashboard/filter/new'
    | '/dashboard/folder/$folderId'
    | '/dashboard/filter';
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/$articleId'
    | '/dashboard/hidden'
    | '/dashboard/search'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/feed/$feedId'
    | '/dashboard/filter/$filterId'
    | '/dashboard/filter/new'
    | '/dashboard/folder/$folderId'
    | '/dashboard/filter/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/settings': {
      id: '/dashboard/settings';
      path: '/settings';
      fullPath: '/dashboard/settings';
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/search': {
      id: '/dashboard/search';
      path: '/search';
      fullPath: '/dashboard/search';
      preLoaderRoute: typeof DashboardSearchRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/hidden': {
      id: '/dashboard/hidden';
      path: '/hidden';
      fullPath: '/dashboard/hidden';
      preLoaderRoute: typeof DashboardHiddenRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/$articleId': {
      id: '/dashboard/$articleId';
      path: '/$articleId';
      fullPath: '/dashboard/$articleId';
      preLoaderRoute: typeof DashboardArticleIdRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/filter/': {
      id: '/dashboard/filter/';
      path: '/filter';
      fullPath: '/dashboard/filter';
      preLoaderRoute: typeof DashboardFilterIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/folder/$folderId': {
      id: '/dashboard/folder/$folderId';
      path: '/folder/$folderId';
      fullPath: '/dashboard/folder/$folderId';
      preLoaderRoute: typeof DashboardFolderFolderIdRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/filter/new': {
      id: '/dashboard/filter/new';
      path: '/filter/new';
      fullPath: '/dashboard/filter/new';
      preLoaderRoute: typeof DashboardFilterNewRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/filter/$filterId': {
      id: '/dashboard/filter/$filterId';
      path: '/filter/$filterId';
      fullPath: '/dashboard/filter/$filterId';
      preLoaderRoute: typeof DashboardFilterFilterIdRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    '/dashboard/feed/$feedId': {
      id: '/dashboard/feed/$feedId';
      path: '/feed/$feedId';
      fullPath: '/dashboard/feed/$feedId';
      preLoaderRoute: typeof DashboardFeedFeedIdRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
  }
}

interface DashboardRouteRouteChildren {
  DashboardArticleIdRoute: typeof DashboardArticleIdRoute;
  DashboardHiddenRoute: typeof DashboardHiddenRoute;
  DashboardSearchRoute: typeof DashboardSearchRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardFeedFeedIdRoute: typeof DashboardFeedFeedIdRoute;
  DashboardFilterFilterIdRoute: typeof DashboardFilterFilterIdRoute;
  DashboardFilterNewRoute: typeof DashboardFilterNewRoute;
  DashboardFolderFolderIdRoute: typeof DashboardFolderFolderIdRoute;
  DashboardFilterIndexRoute: typeof DashboardFilterIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardArticleIdRoute: DashboardArticleIdRoute,
  DashboardFeedFeedIdRoute: DashboardFeedFeedIdRoute,
  DashboardFilterFilterIdRoute: DashboardFilterFilterIdRoute,
  DashboardFilterIndexRoute: DashboardFilterIndexRoute,
  DashboardFilterNewRoute: DashboardFilterNewRoute,
  DashboardFolderFolderIdRoute: DashboardFolderFolderIdRoute,
  DashboardHiddenRoute: DashboardHiddenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
