/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMutation } from '@tanstack/react-query';

import type { CreateBookmarkDto, CreateConfigDto } from '../model';

export type readlaterControllerCreateConfigResponse201 = {
  data: void;
  status: 201;
};

export type readlaterControllerCreateConfigResponse401 = {
  data: void;
  status: 401;
};

export type readlaterControllerCreateConfigResponse500 = {
  data: void;
  status: 500;
};

export type readlaterControllerCreateConfigResponseSuccess =
  readlaterControllerCreateConfigResponse201 & {
    headers: Headers;
  };
export type readlaterControllerCreateConfigResponseError = (
  | readlaterControllerCreateConfigResponse401
  | readlaterControllerCreateConfigResponse500
) & {
  headers: Headers;
};

export type readlaterControllerCreateConfigResponse =
  | readlaterControllerCreateConfigResponseSuccess
  | readlaterControllerCreateConfigResponseError;

export const getReadlaterControllerCreateConfigUrl = () => {
  return `/readlater/configure`;
};

export const readlaterControllerCreateConfig = async (
  createConfigDto: CreateConfigDto,
  options?: RequestInit,
): Promise<readlaterControllerCreateConfigResponse> => {
  const res = await fetch(getReadlaterControllerCreateConfigUrl(), {
    ...options,
    body: JSON.stringify(createConfigDto),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readlaterControllerCreateConfigResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as readlaterControllerCreateConfigResponse;
};

export const getReadlaterControllerCreateConfigMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof readlaterControllerCreateConfig>>,
    TError,
    { data: CreateConfigDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof readlaterControllerCreateConfig>>,
  TError,
  { data: CreateConfigDto },
  TContext
> => {
  const mutationKey = ['readlaterControllerCreateConfig'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof readlaterControllerCreateConfig>>,
    { data: CreateConfigDto }
  > = (props) => {
    const { data } = props ?? {};

    return readlaterControllerCreateConfig(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReadlaterControllerCreateConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof readlaterControllerCreateConfig>>
>;
export type ReadlaterControllerCreateConfigMutationBody = CreateConfigDto;
export type ReadlaterControllerCreateConfigMutationError = void;

export const useReadlaterControllerCreateConfig = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof readlaterControllerCreateConfig>>,
      TError,
      { data: CreateConfigDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof readlaterControllerCreateConfig>>,
  TError,
  { data: CreateConfigDto },
  TContext
> => {
  return useMutation(
    getReadlaterControllerCreateConfigMutationOptions(options),
    queryClient,
  );
};
export type readlaterControllerAddBookmarkResponse201 = {
  data: void;
  status: 201;
};

export type readlaterControllerAddBookmarkResponse401 = {
  data: void;
  status: 401;
};

export type readlaterControllerAddBookmarkResponse412 = {
  data: void;
  status: 412;
};

export type readlaterControllerAddBookmarkResponse500 = {
  data: void;
  status: 500;
};

export type readlaterControllerAddBookmarkResponseSuccess =
  readlaterControllerAddBookmarkResponse201 & {
    headers: Headers;
  };
export type readlaterControllerAddBookmarkResponseError = (
  | readlaterControllerAddBookmarkResponse401
  | readlaterControllerAddBookmarkResponse412
  | readlaterControllerAddBookmarkResponse500
) & {
  headers: Headers;
};

export type readlaterControllerAddBookmarkResponse =
  | readlaterControllerAddBookmarkResponseSuccess
  | readlaterControllerAddBookmarkResponseError;

export const getReadlaterControllerAddBookmarkUrl = () => {
  return `/readlater`;
};

export const readlaterControllerAddBookmark = async (
  createBookmarkDto: CreateBookmarkDto,
  options?: RequestInit,
): Promise<readlaterControllerAddBookmarkResponse> => {
  const res = await fetch(getReadlaterControllerAddBookmarkUrl(), {
    ...options,
    body: JSON.stringify(createBookmarkDto),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readlaterControllerAddBookmarkResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as readlaterControllerAddBookmarkResponse;
};

export const getReadlaterControllerAddBookmarkMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof readlaterControllerAddBookmark>>,
    TError,
    { data: CreateBookmarkDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof readlaterControllerAddBookmark>>,
  TError,
  { data: CreateBookmarkDto },
  TContext
> => {
  const mutationKey = ['readlaterControllerAddBookmark'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof readlaterControllerAddBookmark>>,
    { data: CreateBookmarkDto }
  > = (props) => {
    const { data } = props ?? {};

    return readlaterControllerAddBookmark(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReadlaterControllerAddBookmarkMutationResult = NonNullable<
  Awaited<ReturnType<typeof readlaterControllerAddBookmark>>
>;
export type ReadlaterControllerAddBookmarkMutationBody = CreateBookmarkDto;
export type ReadlaterControllerAddBookmarkMutationError = void;

export const useReadlaterControllerAddBookmark = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof readlaterControllerAddBookmark>>,
      TError,
      { data: CreateBookmarkDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof readlaterControllerAddBookmark>>,
  TError,
  { data: CreateBookmarkDto },
  TContext
> => {
  return useMutation(
    getReadlaterControllerAddBookmarkMutationOptions(options),
    queryClient,
  );
};
