/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { HttpResponse, http } from 'msw';

import type {
  DiscoverOutDtoOutput,
  FeedOutWithCountsDtoOutput,
  NewSubscriptionDtoOutput,
  SubscriptionOutDtoOutput,
} from '../model';

export const getFeedControllerCreateResponseMock = (
  overrideResponse: Partial<Extract<NewSubscriptionDtoOutput, object>> = {},
): NewSubscriptionDtoOutput => ({
  authors: Array.from(
    { length: faker.number.int({ max: 10, min: 1 }) },
    (_, i) => i + 1,
  ).map(() => ({
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    name: faker.string.alpha({ length: { max: 20, min: 10 } }),
    uri: faker.helpers.arrayElement([faker.internet.url(), undefined]),
  })),
  categories: Array.from(
    { length: faker.number.int({ max: 10, min: 1 }) },
    (_, i) => i + 1,
  ).map(() => ({
    label: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      undefined,
    ]),
    scheme: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      undefined,
    ]),
    term: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      undefined,
    ]),
  })),
  contributors: Array.from(
    { length: faker.number.int({ max: 10, min: 1 }) },
    (_, i) => i + 1,
  ).map(() => ({
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    name: faker.string.alpha({ length: { max: 20, min: 10 } }),
    uri: faker.helpers.arrayElement([faker.internet.url(), undefined]),
  })),
  copyright: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  crawler: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
  etag_header: faker.string.alpha({ length: { max: 20, min: 10 } }),
  explicit: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
  geo: faker.helpers.arrayElement([
    {
      box: faker.helpers.arrayElement([
        {
          lowerCorner: {
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          },
          upperCorner: {
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          },
        },
        undefined,
      ]),
      elev: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        undefined,
      ]),
      featureName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      featureTypeTag: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      floor: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        undefined,
      ]),
      line: faker.helpers.arrayElement([
        {
          points: Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => ({
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          })),
        },
        undefined,
      ]),
      point: faker.helpers.arrayElement([
        {
          lat: faker.number.float({ fractionDigits: 2 }),
          lng: faker.number.float({ fractionDigits: 2 }),
        },
        undefined,
      ]),
      polygon: faker.helpers.arrayElement([
        {
          points: Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => ({
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          })),
        },
        undefined,
      ]),
      radius: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        undefined,
      ]),
      relationshipTag: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
    },
    null,
  ]),
  id: faker.string.uuid(),
  image: faker.helpers.arrayElement([
    {
      description: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      height: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2, min: 0 }),
        undefined,
      ]),
      link: faker.internet.url(),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      url: faker.internet.url(),
      width: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2, min: 0 }),
        undefined,
      ]),
    },
    null,
  ]),
  last_modified_header: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  lastChecked: faker.date.past().toISOString().slice(0, 19) + 'Z',
  minifluxId: faker.number.float({ fractionDigits: 2, min: 0 }),
  parsingErrorCount: faker.number.float({ fractionDigits: 2, min: 0 }),
  parsingErrorMessage: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  podcast: faker.helpers.arrayElement([
    {
      blocks: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          value: faker.datatype.boolean(),
        })),
        undefined,
      ]),
      fundings: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          url: faker.internet.url(),
        })),
        undefined,
      ]),
      guid: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      images: faker.helpers.arrayElement([
        {
          srcset: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      liveItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          contentLinks: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              display: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              href: faker.internet.url(),
            })),
            undefined,
          ]),
          end: faker.helpers.arrayElement([
            faker.date.past().toISOString().slice(0, 19) + 'Z',
            undefined,
          ]),
          start: faker.date.past().toISOString().slice(0, 19) + 'Z',
          status: faker.string.alpha({ length: { max: 20, min: 10 } }),
        })),
        undefined,
      ]),
      location: faker.helpers.arrayElement([
        {
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          geo: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          osm: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      locked: faker.helpers.arrayElement([
        {
          owner: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          value: faker.datatype.boolean(),
        },
        undefined,
      ]),
      medium: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      persons: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          group: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          href: faker.helpers.arrayElement([faker.internet.url(), undefined]),
          img: faker.helpers.arrayElement([faker.internet.url(), undefined]),
          role: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      podping: faker.helpers.arrayElement([
        {
          usesPodping: faker.helpers.arrayElement([
            faker.datatype.boolean(),
            undefined,
          ]),
        },
        undefined,
      ]),
      podroll: faker.helpers.arrayElement([
        {
          remoteItems: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              feedGuid: faker.string.alpha({ length: { max: 20, min: 10 } }),
              feedUrl: faker.helpers.arrayElement([
                faker.internet.url(),
                undefined,
              ]),
              itemGuid: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              medium: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            })),
            undefined,
          ]),
        },
        undefined,
      ]),
      remoteItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          feedGuid: faker.string.alpha({ length: { max: 20, min: 10 } }),
          feedUrl: faker.helpers.arrayElement([
            faker.internet.url(),
            undefined,
          ]),
          itemGuid: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          medium: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      trailers: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          length: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2, min: 0 }),
            undefined,
          ]),
          pubDate: faker.string.alpha({ length: { max: 20, min: 10 } }),
          season: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2 }),
            undefined,
          ]),
          type: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          url: faker.internet.url(),
        })),
        undefined,
      ]),
      txts: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          purpose: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      updateFrequency: faker.helpers.arrayElement([
        {
          complete: faker.helpers.arrayElement([
            faker.datatype.boolean(),
            undefined,
          ]),
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          dtstart: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          rrule: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      value: faker.helpers.arrayElement([
        {
          method: faker.string.alpha({ length: { max: 20, min: 10 } }),
          suggested: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2, min: 0 }),
            undefined,
          ]),
          type: faker.string.alpha({ length: { max: 20, min: 10 } }),
          valueRecipients: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              address: faker.string.alpha({ length: { max: 20, min: 10 } }),
              customKey: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              customValue: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              fee: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
              name: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              split: faker.number.float({ fractionDigits: 2, min: 0 }),
              type: faker.string.alpha({ length: { max: 20, min: 10 } }),
            })),
            undefined,
          ]),
          valueTimeSplits: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              duration: faker.number.float({ fractionDigits: 2, min: 0 }),
              remoteItem: faker.helpers.arrayElement([
                {
                  feedGuid: faker.string.alpha({
                    length: { max: 20, min: 10 },
                  }),
                  feedUrl: faker.helpers.arrayElement([
                    faker.internet.url(),
                    undefined,
                  ]),
                  itemGuid: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  medium: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                },
                undefined,
              ]),
              remotePercentage: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2, min: 0 }),
                undefined,
              ]),
              remoteStartTime: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2, min: 0 }),
                undefined,
              ]),
              startTime: faker.number.float({ fractionDigits: 2, min: 0 }),
              valueRecipients: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ max: 10, min: 1 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  address: faker.string.alpha({ length: { max: 20, min: 10 } }),
                  customKey: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  customValue: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  fee: faker.helpers.arrayElement([
                    faker.datatype.boolean(),
                    undefined,
                  ]),
                  name: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  split: faker.number.float({ fractionDigits: 2, min: 0 }),
                  type: faker.string.alpha({ length: { max: 20, min: 10 } }),
                })),
                undefined,
              ]),
            })),
            undefined,
          ]),
        },
        undefined,
      ]),
    },
    null,
  ]),
  publisher: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  rights: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  site_url: faker.helpers.arrayElement([faker.internet.url(), null]),
  subject: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  subscription: {
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      null,
    ]),
    feedId: faker.string.uuid(),
    folderId: faker.helpers.arrayElement([faker.string.uuid(), null]),
    id: faker.string.uuid(),
    userId: faker.string.alpha({ length: { max: 20, min: 10 } }),
  },
  subtitle: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  title: faker.string.alpha({ length: { max: 20, min: 10 } }),
  updateBase: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  updated: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + 'Z',
    null,
  ]),
  updateFrequency: faker.helpers.arrayElement([
    faker.number.float({ fractionDigits: 2 }),
    null,
  ]),
  updatePeriod: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  url: faker.internet.url(),
  userAgent: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  youtube: faker.helpers.arrayElement([
    {
      channelId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      playlistId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
    },
    null,
  ]),
  ...overrideResponse,
});

export const getFeedControllerFindAllResponseMock =
  (): FeedOutWithCountsDtoOutput[] =>
    Array.from(
      { length: faker.number.int({ max: 10, min: 1 }) },
      (_, i) => i + 1,
    ).map(() => ({
      authors: Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => ({
        email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
        name: faker.string.alpha({ length: { max: 20, min: 10 } }),
        uri: faker.helpers.arrayElement([faker.internet.url(), undefined]),
      })),
      categories: Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => ({
        label: faker.helpers.arrayElement([
          faker.string.alpha({ length: { max: 20, min: 10 } }),
          undefined,
        ]),
        scheme: faker.helpers.arrayElement([
          faker.string.alpha({ length: { max: 20, min: 10 } }),
          undefined,
        ]),
        term: faker.helpers.arrayElement([
          faker.string.alpha({ length: { max: 20, min: 10 } }),
          undefined,
        ]),
      })),
      contributors: Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => ({
        email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
        name: faker.string.alpha({ length: { max: 20, min: 10 } }),
        uri: faker.helpers.arrayElement([faker.internet.url(), undefined]),
      })),
      copyright: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      crawler: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
      etag_header: faker.string.alpha({ length: { max: 20, min: 10 } }),
      explicit: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
      favicon: faker.helpers.arrayElement([faker.internet.url(), null]),
      folderId: faker.helpers.arrayElement([faker.string.uuid(), null]),
      geo: faker.helpers.arrayElement([
        {
          box: faker.helpers.arrayElement([
            {
              lowerCorner: {
                lat: faker.number.float({ fractionDigits: 2 }),
                lng: faker.number.float({ fractionDigits: 2 }),
              },
              upperCorner: {
                lat: faker.number.float({ fractionDigits: 2 }),
                lng: faker.number.float({ fractionDigits: 2 }),
              },
            },
            undefined,
          ]),
          elev: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2 }),
            undefined,
          ]),
          featureName: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          featureTypeTag: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          floor: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2 }),
            undefined,
          ]),
          line: faker.helpers.arrayElement([
            {
              points: Array.from(
                { length: faker.number.int({ max: 10, min: 1 }) },
                (_, i) => i + 1,
              ).map(() => ({
                lat: faker.number.float({ fractionDigits: 2 }),
                lng: faker.number.float({ fractionDigits: 2 }),
              })),
            },
            undefined,
          ]),
          point: faker.helpers.arrayElement([
            {
              lat: faker.number.float({ fractionDigits: 2 }),
              lng: faker.number.float({ fractionDigits: 2 }),
            },
            undefined,
          ]),
          polygon: faker.helpers.arrayElement([
            {
              points: Array.from(
                { length: faker.number.int({ max: 10, min: 1 }) },
                (_, i) => i + 1,
              ).map(() => ({
                lat: faker.number.float({ fractionDigits: 2 }),
                lng: faker.number.float({ fractionDigits: 2 }),
              })),
            },
            undefined,
          ]),
          radius: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2 }),
            undefined,
          ]),
          relationshipTag: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        null,
      ]),
      id: faker.string.uuid(),
      image: faker.helpers.arrayElement([
        {
          description: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          height: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2, min: 0 }),
            undefined,
          ]),
          link: faker.internet.url(),
          title: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          url: faker.internet.url(),
          width: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2, min: 0 }),
            undefined,
          ]),
        },
        null,
      ]),
      last_modified_header: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      lastChecked: faker.date.past().toISOString().slice(0, 19) + 'Z',
      parsingErrorCount: faker.number.float({ fractionDigits: 2, min: 0 }),
      parsingErrorMessage: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      podcast: faker.helpers.arrayElement([
        {
          blocks: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              id: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              value: faker.datatype.boolean(),
            })),
            undefined,
          ]),
          fundings: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              display: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              url: faker.internet.url(),
            })),
            undefined,
          ]),
          guid: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          images: faker.helpers.arrayElement([
            {
              srcset: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            },
            undefined,
          ]),
          liveItems: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              contentLinks: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ max: 10, min: 1 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  display: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  href: faker.internet.url(),
                })),
                undefined,
              ]),
              end: faker.helpers.arrayElement([
                faker.date.past().toISOString().slice(0, 19) + 'Z',
                undefined,
              ]),
              start: faker.date.past().toISOString().slice(0, 19) + 'Z',
              status: faker.string.alpha({ length: { max: 20, min: 10 } }),
            })),
            undefined,
          ]),
          location: faker.helpers.arrayElement([
            {
              display: faker.string.alpha({ length: { max: 20, min: 10 } }),
              geo: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              osm: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            },
            undefined,
          ]),
          locked: faker.helpers.arrayElement([
            {
              owner: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              value: faker.datatype.boolean(),
            },
            undefined,
          ]),
          medium: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          persons: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              display: faker.string.alpha({ length: { max: 20, min: 10 } }),
              group: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              href: faker.helpers.arrayElement([
                faker.internet.url(),
                undefined,
              ]),
              img: faker.helpers.arrayElement([
                faker.internet.url(),
                undefined,
              ]),
              role: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          podping: faker.helpers.arrayElement([
            {
              usesPodping: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
            },
            undefined,
          ]),
          podroll: faker.helpers.arrayElement([
            {
              remoteItems: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ max: 10, min: 1 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  feedGuid: faker.string.alpha({
                    length: { max: 20, min: 10 },
                  }),
                  feedUrl: faker.helpers.arrayElement([
                    faker.internet.url(),
                    undefined,
                  ]),
                  itemGuid: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  medium: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
            },
            undefined,
          ]),
          remoteItems: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              feedGuid: faker.string.alpha({ length: { max: 20, min: 10 } }),
              feedUrl: faker.helpers.arrayElement([
                faker.internet.url(),
                undefined,
              ]),
              itemGuid: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              medium: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          trailers: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              display: faker.string.alpha({ length: { max: 20, min: 10 } }),
              length: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2, min: 0 }),
                undefined,
              ]),
              pubDate: faker.string.alpha({ length: { max: 20, min: 10 } }),
              season: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2 }),
                undefined,
              ]),
              type: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              url: faker.internet.url(),
            })),
            undefined,
          ]),
          txts: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              display: faker.string.alpha({ length: { max: 20, min: 10 } }),
              purpose: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            })),
            undefined,
          ]),
          updateFrequency: faker.helpers.arrayElement([
            {
              complete: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
              display: faker.string.alpha({ length: { max: 20, min: 10 } }),
              dtstart: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              rrule: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            },
            undefined,
          ]),
          value: faker.helpers.arrayElement([
            {
              method: faker.string.alpha({ length: { max: 20, min: 10 } }),
              suggested: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2, min: 0 }),
                undefined,
              ]),
              type: faker.string.alpha({ length: { max: 20, min: 10 } }),
              valueRecipients: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ max: 10, min: 1 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  address: faker.string.alpha({ length: { max: 20, min: 10 } }),
                  customKey: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  customValue: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  fee: faker.helpers.arrayElement([
                    faker.datatype.boolean(),
                    undefined,
                  ]),
                  name: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  split: faker.number.float({ fractionDigits: 2, min: 0 }),
                  type: faker.string.alpha({ length: { max: 20, min: 10 } }),
                })),
                undefined,
              ]),
              valueTimeSplits: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ max: 10, min: 1 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  duration: faker.number.float({ fractionDigits: 2, min: 0 }),
                  remoteItem: faker.helpers.arrayElement([
                    {
                      feedGuid: faker.string.alpha({
                        length: { max: 20, min: 10 },
                      }),
                      feedUrl: faker.helpers.arrayElement([
                        faker.internet.url(),
                        undefined,
                      ]),
                      itemGuid: faker.helpers.arrayElement([
                        faker.string.alpha({ length: { max: 20, min: 10 } }),
                        undefined,
                      ]),
                      medium: faker.helpers.arrayElement([
                        faker.string.alpha({ length: { max: 20, min: 10 } }),
                        undefined,
                      ]),
                    },
                    undefined,
                  ]),
                  remotePercentage: faker.helpers.arrayElement([
                    faker.number.float({ fractionDigits: 2, min: 0 }),
                    undefined,
                  ]),
                  remoteStartTime: faker.helpers.arrayElement([
                    faker.number.float({ fractionDigits: 2, min: 0 }),
                    undefined,
                  ]),
                  startTime: faker.number.float({ fractionDigits: 2, min: 0 }),
                  valueRecipients: faker.helpers.arrayElement([
                    Array.from(
                      { length: faker.number.int({ max: 10, min: 1 }) },
                      (_, i) => i + 1,
                    ).map(() => ({
                      address: faker.string.alpha({
                        length: { max: 20, min: 10 },
                      }),
                      customKey: faker.helpers.arrayElement([
                        faker.string.alpha({ length: { max: 20, min: 10 } }),
                        undefined,
                      ]),
                      customValue: faker.helpers.arrayElement([
                        faker.string.alpha({ length: { max: 20, min: 10 } }),
                        undefined,
                      ]),
                      fee: faker.helpers.arrayElement([
                        faker.datatype.boolean(),
                        undefined,
                      ]),
                      name: faker.helpers.arrayElement([
                        faker.string.alpha({ length: { max: 20, min: 10 } }),
                        undefined,
                      ]),
                      split: faker.number.float({ fractionDigits: 2, min: 0 }),
                      type: faker.string.alpha({
                        length: { max: 20, min: 10 },
                      }),
                    })),
                    undefined,
                  ]),
                })),
                undefined,
              ]),
            },
            undefined,
          ]),
        },
        null,
      ]),
      publisher: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      rights: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      site_url: faker.helpers.arrayElement([faker.internet.url(), null]),
      subject: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      subtitle: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      title: faker.string.alpha({ length: { max: 20, min: 10 } }),
      unreadCount: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2, min: 0 }),
        null,
      ]),
      updateBase: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      updated: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + 'Z',
        null,
      ]),
      updateFrequency: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        null,
      ]),
      updatePeriod: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      url: faker.internet.url(),
      userAgent: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        null,
      ]),
      youtube: faker.helpers.arrayElement([
        {
          channelId: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          playlistId: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        null,
      ]),
    }));

export const getFeedControllerDiscoverResponseMock =
  (): DiscoverOutDtoOutput[] =>
    Array.from(
      { length: faker.number.int({ max: 10, min: 1 }) },
      (_, i) => i + 1,
    ).map(() => ({
      format: faker.string.alpha({ length: { max: 20, min: 10 } }),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 255, min: 1 } }),
        null,
      ]),
      url: faker.internet.url(),
    }));

export const getFeedControllerFindOneResponseMock = (
  overrideResponse: Partial<Extract<FeedOutWithCountsDtoOutput, object>> = {},
): FeedOutWithCountsDtoOutput => ({
  authors: Array.from(
    { length: faker.number.int({ max: 10, min: 1 }) },
    (_, i) => i + 1,
  ).map(() => ({
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    name: faker.string.alpha({ length: { max: 20, min: 10 } }),
    uri: faker.helpers.arrayElement([faker.internet.url(), undefined]),
  })),
  categories: Array.from(
    { length: faker.number.int({ max: 10, min: 1 }) },
    (_, i) => i + 1,
  ).map(() => ({
    label: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      undefined,
    ]),
    scheme: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      undefined,
    ]),
    term: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 20, min: 10 } }),
      undefined,
    ]),
  })),
  contributors: Array.from(
    { length: faker.number.int({ max: 10, min: 1 }) },
    (_, i) => i + 1,
  ).map(() => ({
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    name: faker.string.alpha({ length: { max: 20, min: 10 } }),
    uri: faker.helpers.arrayElement([faker.internet.url(), undefined]),
  })),
  copyright: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  crawler: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
  etag_header: faker.string.alpha({ length: { max: 20, min: 10 } }),
  explicit: faker.helpers.arrayElement([faker.datatype.boolean(), null]),
  favicon: faker.helpers.arrayElement([faker.internet.url(), null]),
  folderId: faker.helpers.arrayElement([faker.string.uuid(), null]),
  geo: faker.helpers.arrayElement([
    {
      box: faker.helpers.arrayElement([
        {
          lowerCorner: {
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          },
          upperCorner: {
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          },
        },
        undefined,
      ]),
      elev: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        undefined,
      ]),
      featureName: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      featureTypeTag: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      floor: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        undefined,
      ]),
      line: faker.helpers.arrayElement([
        {
          points: Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => ({
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          })),
        },
        undefined,
      ]),
      point: faker.helpers.arrayElement([
        {
          lat: faker.number.float({ fractionDigits: 2 }),
          lng: faker.number.float({ fractionDigits: 2 }),
        },
        undefined,
      ]),
      polygon: faker.helpers.arrayElement([
        {
          points: Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => ({
            lat: faker.number.float({ fractionDigits: 2 }),
            lng: faker.number.float({ fractionDigits: 2 }),
          })),
        },
        undefined,
      ]),
      radius: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2 }),
        undefined,
      ]),
      relationshipTag: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
    },
    null,
  ]),
  id: faker.string.uuid(),
  image: faker.helpers.arrayElement([
    {
      description: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      height: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2, min: 0 }),
        undefined,
      ]),
      link: faker.internet.url(),
      title: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      url: faker.internet.url(),
      width: faker.helpers.arrayElement([
        faker.number.float({ fractionDigits: 2, min: 0 }),
        undefined,
      ]),
    },
    null,
  ]),
  last_modified_header: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  lastChecked: faker.date.past().toISOString().slice(0, 19) + 'Z',
  parsingErrorCount: faker.number.float({ fractionDigits: 2, min: 0 }),
  parsingErrorMessage: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  podcast: faker.helpers.arrayElement([
    {
      blocks: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          value: faker.datatype.boolean(),
        })),
        undefined,
      ]),
      fundings: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          url: faker.internet.url(),
        })),
        undefined,
      ]),
      guid: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      images: faker.helpers.arrayElement([
        {
          srcset: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      liveItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          contentLinks: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              display: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              href: faker.internet.url(),
            })),
            undefined,
          ]),
          end: faker.helpers.arrayElement([
            faker.date.past().toISOString().slice(0, 19) + 'Z',
            undefined,
          ]),
          start: faker.date.past().toISOString().slice(0, 19) + 'Z',
          status: faker.string.alpha({ length: { max: 20, min: 10 } }),
        })),
        undefined,
      ]),
      location: faker.helpers.arrayElement([
        {
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          geo: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          osm: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      locked: faker.helpers.arrayElement([
        {
          owner: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          value: faker.datatype.boolean(),
        },
        undefined,
      ]),
      medium: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      persons: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          group: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          href: faker.helpers.arrayElement([faker.internet.url(), undefined]),
          img: faker.helpers.arrayElement([faker.internet.url(), undefined]),
          role: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      podping: faker.helpers.arrayElement([
        {
          usesPodping: faker.helpers.arrayElement([
            faker.datatype.boolean(),
            undefined,
          ]),
        },
        undefined,
      ]),
      podroll: faker.helpers.arrayElement([
        {
          remoteItems: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              feedGuid: faker.string.alpha({ length: { max: 20, min: 10 } }),
              feedUrl: faker.helpers.arrayElement([
                faker.internet.url(),
                undefined,
              ]),
              itemGuid: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              medium: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
            })),
            undefined,
          ]),
        },
        undefined,
      ]),
      remoteItems: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          feedGuid: faker.string.alpha({ length: { max: 20, min: 10 } }),
          feedUrl: faker.helpers.arrayElement([
            faker.internet.url(),
            undefined,
          ]),
          itemGuid: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          medium: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      trailers: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          length: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2, min: 0 }),
            undefined,
          ]),
          pubDate: faker.string.alpha({ length: { max: 20, min: 10 } }),
          season: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2 }),
            undefined,
          ]),
          type: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          url: faker.internet.url(),
        })),
        undefined,
      ]),
      txts: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ max: 10, min: 1 }) },
          (_, i) => i + 1,
        ).map(() => ({
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          purpose: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      updateFrequency: faker.helpers.arrayElement([
        {
          complete: faker.helpers.arrayElement([
            faker.datatype.boolean(),
            undefined,
          ]),
          display: faker.string.alpha({ length: { max: 20, min: 10 } }),
          dtstart: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
          rrule: faker.helpers.arrayElement([
            faker.string.alpha({ length: { max: 20, min: 10 } }),
            undefined,
          ]),
        },
        undefined,
      ]),
      value: faker.helpers.arrayElement([
        {
          method: faker.string.alpha({ length: { max: 20, min: 10 } }),
          suggested: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2, min: 0 }),
            undefined,
          ]),
          type: faker.string.alpha({ length: { max: 20, min: 10 } }),
          valueRecipients: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              address: faker.string.alpha({ length: { max: 20, min: 10 } }),
              customKey: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              customValue: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              fee: faker.helpers.arrayElement([
                faker.datatype.boolean(),
                undefined,
              ]),
              name: faker.helpers.arrayElement([
                faker.string.alpha({ length: { max: 20, min: 10 } }),
                undefined,
              ]),
              split: faker.number.float({ fractionDigits: 2, min: 0 }),
              type: faker.string.alpha({ length: { max: 20, min: 10 } }),
            })),
            undefined,
          ]),
          valueTimeSplits: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ max: 10, min: 1 }) },
              (_, i) => i + 1,
            ).map(() => ({
              duration: faker.number.float({ fractionDigits: 2, min: 0 }),
              remoteItem: faker.helpers.arrayElement([
                {
                  feedGuid: faker.string.alpha({
                    length: { max: 20, min: 10 },
                  }),
                  feedUrl: faker.helpers.arrayElement([
                    faker.internet.url(),
                    undefined,
                  ]),
                  itemGuid: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  medium: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                },
                undefined,
              ]),
              remotePercentage: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2, min: 0 }),
                undefined,
              ]),
              remoteStartTime: faker.helpers.arrayElement([
                faker.number.float({ fractionDigits: 2, min: 0 }),
                undefined,
              ]),
              startTime: faker.number.float({ fractionDigits: 2, min: 0 }),
              valueRecipients: faker.helpers.arrayElement([
                Array.from(
                  { length: faker.number.int({ max: 10, min: 1 }) },
                  (_, i) => i + 1,
                ).map(() => ({
                  address: faker.string.alpha({ length: { max: 20, min: 10 } }),
                  customKey: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  customValue: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  fee: faker.helpers.arrayElement([
                    faker.datatype.boolean(),
                    undefined,
                  ]),
                  name: faker.helpers.arrayElement([
                    faker.string.alpha({ length: { max: 20, min: 10 } }),
                    undefined,
                  ]),
                  split: faker.number.float({ fractionDigits: 2, min: 0 }),
                  type: faker.string.alpha({ length: { max: 20, min: 10 } }),
                })),
                undefined,
              ]),
            })),
            undefined,
          ]),
        },
        undefined,
      ]),
    },
    null,
  ]),
  publisher: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  rights: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  site_url: faker.helpers.arrayElement([faker.internet.url(), null]),
  subject: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  subtitle: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  title: faker.string.alpha({ length: { max: 20, min: 10 } }),
  unreadCount: faker.helpers.arrayElement([
    faker.number.float({ fractionDigits: 2, min: 0 }),
    null,
  ]),
  updateBase: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  updated: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 19) + 'Z',
    null,
  ]),
  updateFrequency: faker.helpers.arrayElement([
    faker.number.float({ fractionDigits: 2 }),
    null,
  ]),
  updatePeriod: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  url: faker.internet.url(),
  userAgent: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  youtube: faker.helpers.arrayElement([
    {
      channelId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
      playlistId: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 20, min: 10 } }),
        undefined,
      ]),
    },
    null,
  ]),
  ...overrideResponse,
});

export const getFeedControllerUpdateResponseMock = (
  overrideResponse: Partial<Extract<SubscriptionOutDtoOutput, object>> = {},
): SubscriptionOutDtoOutput => ({
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 20, min: 10 } }),
    null,
  ]),
  feedId: faker.string.uuid(),
  folderId: faker.helpers.arrayElement([faker.string.uuid(), null]),
  id: faker.string.uuid(),
  userId: faker.string.alpha({ length: { max: 20, min: 10 } }),
  ...overrideResponse,
});

export const getFeedControllerCreateMockHandler = (
  overrideResponse?:
    | NewSubscriptionDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<NewSubscriptionDtoOutput> | NewSubscriptionDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/feed',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFeedControllerCreateResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getFeedControllerFindAllMockHandler = (
  overrideResponse?:
    | FeedOutWithCountsDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<FeedOutWithCountsDtoOutput[]>
        | FeedOutWithCountsDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/feed',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFeedControllerFindAllResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getFeedControllerDiscoverMockHandler = (
  overrideResponse?:
    | DiscoverOutDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<DiscoverOutDtoOutput[]> | DiscoverOutDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/feed/discover',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFeedControllerDiscoverResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getFeedControllerImportMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/feed/import',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getFeedControllerExportMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/feed/export',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getFeedControllerMarkAllReadMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/feed/mark-all-read/:id',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};

export const getFeedControllerFindOneMockHandler = (
  overrideResponse?:
    | FeedOutWithCountsDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<FeedOutWithCountsDtoOutput> | FeedOutWithCountsDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/feed/:id',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFeedControllerFindOneResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getFeedControllerRemoveMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/feed/:id',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getFeedControllerUpdateMockHandler = (
  overrideResponse?:
    | SubscriptionOutDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<SubscriptionOutDtoOutput> | SubscriptionOutDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    '*/feed/:id',
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFeedControllerUpdateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getFeedsMock = () => [
  getFeedControllerCreateMockHandler(),
  getFeedControllerFindAllMockHandler(),
  getFeedControllerDiscoverMockHandler(),
  getFeedControllerImportMockHandler(),
  getFeedControllerExportMockHandler(),
  getFeedControllerMarkAllReadMockHandler(),
  getFeedControllerFindOneMockHandler(),
  getFeedControllerRemoveMockHandler(),
  getFeedControllerUpdateMockHandler(),
];
