/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import { faker } from '@faker-js/faker';
import type { RequestHandlerOptions } from 'msw';
import { HttpResponse, http } from 'msw';

import type { FilterOutDtoOutput } from '../model';

export const getFilterControllerCreateResponseMock = (
  overrideResponse: Partial<Extract<FilterOutDtoOutput, object>> = {},
): FilterOutDtoOutput => ({
  action: {
    contentWarning: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 512, min: 10 } }),
      null,
    ]),
    type: faker.helpers.arrayElement(['blur', 'markRead', 'hide'] as const),
  },
  conditions: {
    authors: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    categories: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    contentContains: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    feeds: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    keywords: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    titleContains: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
  },
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 1024, min: 10 } }),
    undefined,
  ]),
  id: faker.string.uuid(),
  isActive: faker.datatype.boolean(),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 255, min: 10 } }),
    null,
  ]),
  ...overrideResponse,
});

export const getFilterControllerFindAllResponseMock =
  (): FilterOutDtoOutput[] =>
    Array.from(
      { length: faker.number.int({ max: 10, min: 1 }) },
      (_, i) => i + 1,
    ).map(() => ({
      action: {
        contentWarning: faker.helpers.arrayElement([
          faker.string.alpha({ length: { max: 512, min: 10 } }),
          null,
        ]),
        type: faker.helpers.arrayElement(['blur', 'markRead', 'hide'] as const),
      },
      conditions: {
        authors: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
          undefined,
        ]),
        categories: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
          undefined,
        ]),
        contentContains: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
          undefined,
        ]),
        feeds: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
          undefined,
        ]),
        keywords: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
          undefined,
        ]),
        titleContains: faker.helpers.arrayElement([
          Array.from(
            { length: faker.number.int({ max: 10, min: 1 }) },
            (_, i) => i + 1,
          ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
          undefined,
        ]),
      },
      description: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 1024, min: 10 } }),
        undefined,
      ]),
      id: faker.string.uuid(),
      isActive: faker.datatype.boolean(),
      name: faker.helpers.arrayElement([
        faker.string.alpha({ length: { max: 255, min: 10 } }),
        null,
      ]),
    }));

export const getFilterControllerFindOneResponseMock = (
  overrideResponse: Partial<Extract<FilterOutDtoOutput, object>> = {},
): FilterOutDtoOutput => ({
  action: {
    contentWarning: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 512, min: 10 } }),
      null,
    ]),
    type: faker.helpers.arrayElement(['blur', 'markRead', 'hide'] as const),
  },
  conditions: {
    authors: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    categories: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    contentContains: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    feeds: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    keywords: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    titleContains: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
  },
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 1024, min: 10 } }),
    undefined,
  ]),
  id: faker.string.uuid(),
  isActive: faker.datatype.boolean(),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 255, min: 10 } }),
    null,
  ]),
  ...overrideResponse,
});

export const getFilterControllerUpdateResponseMock = (
  overrideResponse: Partial<Extract<FilterOutDtoOutput, object>> = {},
): FilterOutDtoOutput => ({
  action: {
    contentWarning: faker.helpers.arrayElement([
      faker.string.alpha({ length: { max: 512, min: 10 } }),
      null,
    ]),
    type: faker.helpers.arrayElement(['blur', 'markRead', 'hide'] as const),
  },
  conditions: {
    authors: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    categories: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    contentContains: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    feeds: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    keywords: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
    titleContains: faker.helpers.arrayElement([
      Array.from(
        { length: faker.number.int({ max: 10, min: 1 }) },
        (_, i) => i + 1,
      ).map(() => faker.string.alpha({ length: { max: 20, min: 10 } })),
      undefined,
    ]),
  },
  description: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 1024, min: 10 } }),
    undefined,
  ]),
  id: faker.string.uuid(),
  isActive: faker.datatype.boolean(),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 255, min: 10 } }),
    null,
  ]),
  ...overrideResponse,
});

export const getFilterControllerCreateMockHandler = (
  overrideResponse?:
    | FilterOutDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<FilterOutDtoOutput> | FilterOutDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/filter',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFilterControllerCreateResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getFilterControllerFindAllMockHandler = (
  overrideResponse?:
    | FilterOutDtoOutput[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<FilterOutDtoOutput[]> | FilterOutDtoOutput[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/filter',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFilterControllerFindAllResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getFilterControllerFindOneMockHandler = (
  overrideResponse?:
    | FilterOutDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<FilterOutDtoOutput> | FilterOutDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/filter/:id',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFilterControllerFindOneResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getFilterControllerUpdateMockHandler = (
  overrideResponse?:
    | FilterOutDtoOutput
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<FilterOutDtoOutput> | FilterOutDtoOutput),
  options?: RequestHandlerOptions,
) => {
  return http.put(
    '*/filter/:id',
    async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getFilterControllerUpdateResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getFilterControllerRemoveMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/filter/:id',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getFilterMock = () => [
  getFilterControllerCreateMockHandler(),
  getFilterControllerFindAllMockHandler(),
  getFilterControllerFindOneMockHandler(),
  getFilterControllerUpdateMockHandler(),
  getFilterControllerRemoveMockHandler(),
];
