/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type {
  CreateFilterDto,
  FilterOutDtoOutput,
  UpdateFilterDto,
} from '../model';

export type filterControllerCreateResponse201 = {
  data: FilterOutDtoOutput;
  status: 201;
};

export type filterControllerCreateResponse401 = {
  data: void;
  status: 401;
};

export type filterControllerCreateResponse500 = {
  data: void;
  status: 500;
};

export type filterControllerCreateResponseSuccess =
  filterControllerCreateResponse201 & {
    headers: Headers;
  };
export type filterControllerCreateResponseError = (
  | filterControllerCreateResponse401
  | filterControllerCreateResponse500
) & {
  headers: Headers;
};

export type filterControllerCreateResponse =
  | filterControllerCreateResponseSuccess
  | filterControllerCreateResponseError;

export const getFilterControllerCreateUrl = () => {
  return `/filter`;
};

export const filterControllerCreate = async (
  createFilterDto: CreateFilterDto,
  options?: RequestInit,
): Promise<filterControllerCreateResponse> => {
  const res = await fetch(getFilterControllerCreateUrl(), {
    ...options,
    body: JSON.stringify(createFilterDto),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filterControllerCreateResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as filterControllerCreateResponse;
};

export const getFilterControllerCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filterControllerCreate>>,
    TError,
    { data: CreateFilterDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filterControllerCreate>>,
  TError,
  { data: CreateFilterDto },
  TContext
> => {
  const mutationKey = ['filterControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filterControllerCreate>>,
    { data: CreateFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return filterControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilterControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof filterControllerCreate>>
>;
export type FilterControllerCreateMutationBody = CreateFilterDto;
export type FilterControllerCreateMutationError = void;

export const useFilterControllerCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filterControllerCreate>>,
      TError,
      { data: CreateFilterDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filterControllerCreate>>,
  TError,
  { data: CreateFilterDto },
  TContext
> => {
  return useMutation(
    getFilterControllerCreateMutationOptions(options),
    queryClient,
  );
};
export type filterControllerFindAllResponse200 = {
  data: FilterOutDtoOutput[];
  status: 200;
};

export type filterControllerFindAllResponse401 = {
  data: void;
  status: 401;
};

export type filterControllerFindAllResponse500 = {
  data: void;
  status: 500;
};

export type filterControllerFindAllResponseSuccess =
  filterControllerFindAllResponse200 & {
    headers: Headers;
  };
export type filterControllerFindAllResponseError = (
  | filterControllerFindAllResponse401
  | filterControllerFindAllResponse500
) & {
  headers: Headers;
};

export type filterControllerFindAllResponse =
  | filterControllerFindAllResponseSuccess
  | filterControllerFindAllResponseError;

export const getFilterControllerFindAllUrl = () => {
  return `/filter`;
};

export const filterControllerFindAll = async (
  options?: RequestInit,
): Promise<filterControllerFindAllResponse> => {
  const res = await fetch(getFilterControllerFindAllUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filterControllerFindAllResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as filterControllerFindAllResponse;
};

export const getFilterControllerFindAllQueryKey = () => {
  return [`/filter`] as const;
};

export const getFilterControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof filterControllerFindAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof filterControllerFindAll>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFilterControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof filterControllerFindAll>>
  > = ({ signal }) => filterControllerFindAll({ signal, ...fetchOptions });

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof filterControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilterControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof filterControllerFindAll>>
>;
export type FilterControllerFindAllQueryError = void;

export function useFilterControllerFindAll<
  TData = Awaited<ReturnType<typeof filterControllerFindAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filterControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof filterControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilterControllerFindAll<
  TData = Awaited<ReturnType<typeof filterControllerFindAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filterControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof filterControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilterControllerFindAll<
  TData = Awaited<ReturnType<typeof filterControllerFindAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFilterControllerFindAll<
  TData = Awaited<ReturnType<typeof filterControllerFindAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFilterControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type filterControllerFindOneResponse200 = {
  data: FilterOutDtoOutput;
  status: 200;
};

export type filterControllerFindOneResponse401 = {
  data: void;
  status: 401;
};

export type filterControllerFindOneResponse500 = {
  data: void;
  status: 500;
};

export type filterControllerFindOneResponseSuccess =
  filterControllerFindOneResponse200 & {
    headers: Headers;
  };
export type filterControllerFindOneResponseError = (
  | filterControllerFindOneResponse401
  | filterControllerFindOneResponse500
) & {
  headers: Headers;
};

export type filterControllerFindOneResponse =
  | filterControllerFindOneResponseSuccess
  | filterControllerFindOneResponseError;

export const getFilterControllerFindOneUrl = (id: string) => {
  return `/filter/${id}`;
};

export const filterControllerFindOne = async (
  id: string,
  options?: RequestInit,
): Promise<filterControllerFindOneResponse> => {
  const res = await fetch(getFilterControllerFindOneUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filterControllerFindOneResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as filterControllerFindOneResponse;
};

export const getFilterControllerFindOneQueryKey = (id: string) => {
  return [`/filter/${id}`] as const;
};

export const getFilterControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof filterControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindOne>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFilterControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof filterControllerFindOne>>
  > = ({ signal }) => filterControllerFindOne(id, { signal, ...fetchOptions });

  return {
    enabled: !!id,
    queryFn,
    queryKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof filterControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilterControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof filterControllerFindOne>>
>;
export type FilterControllerFindOneQueryError = void;

export function useFilterControllerFindOne<
  TData = Awaited<ReturnType<typeof filterControllerFindOne>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filterControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof filterControllerFindOne>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilterControllerFindOne<
  TData = Awaited<ReturnType<typeof filterControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filterControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof filterControllerFindOne>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilterControllerFindOne<
  TData = Awaited<ReturnType<typeof filterControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindOne>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFilterControllerFindOne<
  TData = Awaited<ReturnType<typeof filterControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filterControllerFindOne>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFilterControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type filterControllerUpdateResponse200 = {
  data: FilterOutDtoOutput;
  status: 200;
};

export type filterControllerUpdateResponse401 = {
  data: void;
  status: 401;
};

export type filterControllerUpdateResponse500 = {
  data: void;
  status: 500;
};

export type filterControllerUpdateResponseSuccess =
  filterControllerUpdateResponse200 & {
    headers: Headers;
  };
export type filterControllerUpdateResponseError = (
  | filterControllerUpdateResponse401
  | filterControllerUpdateResponse500
) & {
  headers: Headers;
};

export type filterControllerUpdateResponse =
  | filterControllerUpdateResponseSuccess
  | filterControllerUpdateResponseError;

export const getFilterControllerUpdateUrl = (id: string) => {
  return `/filter/${id}`;
};

export const filterControllerUpdate = async (
  id: string,
  updateFilterDto: UpdateFilterDto,
  options?: RequestInit,
): Promise<filterControllerUpdateResponse> => {
  const res = await fetch(getFilterControllerUpdateUrl(id), {
    ...options,
    body: JSON.stringify(updateFilterDto),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'PUT',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filterControllerUpdateResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as filterControllerUpdateResponse;
};

export const getFilterControllerUpdateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filterControllerUpdate>>,
    TError,
    { id: string; data: UpdateFilterDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filterControllerUpdate>>,
  TError,
  { id: string; data: UpdateFilterDto },
  TContext
> => {
  const mutationKey = ['filterControllerUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filterControllerUpdate>>,
    { id: string; data: UpdateFilterDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return filterControllerUpdate(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilterControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof filterControllerUpdate>>
>;
export type FilterControllerUpdateMutationBody = UpdateFilterDto;
export type FilterControllerUpdateMutationError = void;

export const useFilterControllerUpdate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filterControllerUpdate>>,
      TError,
      { id: string; data: UpdateFilterDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filterControllerUpdate>>,
  TError,
  { id: string; data: UpdateFilterDto },
  TContext
> => {
  return useMutation(
    getFilterControllerUpdateMutationOptions(options),
    queryClient,
  );
};
export type filterControllerRemoveResponse200 = {
  data: void;
  status: 200;
};

export type filterControllerRemoveResponse401 = {
  data: void;
  status: 401;
};

export type filterControllerRemoveResponse500 = {
  data: void;
  status: 500;
};

export type filterControllerRemoveResponseSuccess =
  filterControllerRemoveResponse200 & {
    headers: Headers;
  };
export type filterControllerRemoveResponseError = (
  | filterControllerRemoveResponse401
  | filterControllerRemoveResponse500
) & {
  headers: Headers;
};

export type filterControllerRemoveResponse =
  | filterControllerRemoveResponseSuccess
  | filterControllerRemoveResponseError;

export const getFilterControllerRemoveUrl = (id: string) => {
  return `/filter/${id}`;
};

export const filterControllerRemove = async (
  id: string,
  options?: RequestInit,
): Promise<filterControllerRemoveResponse> => {
  const res = await fetch(getFilterControllerRemoveUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filterControllerRemoveResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as filterControllerRemoveResponse;
};

export const getFilterControllerRemoveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filterControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filterControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['filterControllerRemove'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filterControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return filterControllerRemove(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilterControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof filterControllerRemove>>
>;

export type FilterControllerRemoveMutationError = void;

export const useFilterControllerRemove = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filterControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filterControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getFilterControllerRemoveMutationOptions(options),
    queryClient,
  );
};
