/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import { useMutation, useQuery } from '@tanstack/react-query';

import type {
  CreateFolderDto,
  FolderOutDtoOutput,
  FolderWithFeedsOutDtoOutput,
  UpdateFolderDto,
} from '../model';

export type folderControllerCreateResponse201 = {
  data: FolderOutDtoOutput;
  status: 201;
};

export type folderControllerCreateResponse401 = {
  data: void;
  status: 401;
};

export type folderControllerCreateResponse500 = {
  data: void;
  status: 500;
};

export type folderControllerCreateResponseSuccess =
  folderControllerCreateResponse201 & {
    headers: Headers;
  };
export type folderControllerCreateResponseError = (
  | folderControllerCreateResponse401
  | folderControllerCreateResponse500
) & {
  headers: Headers;
};

export type folderControllerCreateResponse =
  | folderControllerCreateResponseSuccess
  | folderControllerCreateResponseError;

export const getFolderControllerCreateUrl = () => {
  return `/folder`;
};

export const folderControllerCreate = async (
  createFolderDto: CreateFolderDto,
  options?: RequestInit,
): Promise<folderControllerCreateResponse> => {
  const res = await fetch(getFolderControllerCreateUrl(), {
    ...options,
    body: JSON.stringify(createFolderDto),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: folderControllerCreateResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as folderControllerCreateResponse;
};

export const getFolderControllerCreateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof folderControllerCreate>>,
    TError,
    { data: CreateFolderDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof folderControllerCreate>>,
  TError,
  { data: CreateFolderDto },
  TContext
> => {
  const mutationKey = ['folderControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof folderControllerCreate>>,
    { data: CreateFolderDto }
  > = (props) => {
    const { data } = props ?? {};

    return folderControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FolderControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof folderControllerCreate>>
>;
export type FolderControllerCreateMutationBody = CreateFolderDto;
export type FolderControllerCreateMutationError = void;

export const useFolderControllerCreate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof folderControllerCreate>>,
      TError,
      { data: CreateFolderDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof folderControllerCreate>>,
  TError,
  { data: CreateFolderDto },
  TContext
> => {
  return useMutation(
    getFolderControllerCreateMutationOptions(options),
    queryClient,
  );
};
export type folderControllerFindAllResponse200 = {
  data: FolderOutDtoOutput[];
  status: 200;
};

export type folderControllerFindAllResponse401 = {
  data: void;
  status: 401;
};

export type folderControllerFindAllResponse500 = {
  data: void;
  status: 500;
};

export type folderControllerFindAllResponseSuccess =
  folderControllerFindAllResponse200 & {
    headers: Headers;
  };
export type folderControllerFindAllResponseError = (
  | folderControllerFindAllResponse401
  | folderControllerFindAllResponse500
) & {
  headers: Headers;
};

export type folderControllerFindAllResponse =
  | folderControllerFindAllResponseSuccess
  | folderControllerFindAllResponseError;

export const getFolderControllerFindAllUrl = () => {
  return `/folder`;
};

export const folderControllerFindAll = async (
  options?: RequestInit,
): Promise<folderControllerFindAllResponse> => {
  const res = await fetch(getFolderControllerFindAllUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: folderControllerFindAllResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as folderControllerFindAllResponse;
};

export const getFolderControllerFindAllQueryKey = () => {
  return [`/folder`] as const;
};

export const getFolderControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof folderControllerFindAll>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof folderControllerFindAll>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFolderControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof folderControllerFindAll>>
  > = ({ signal }) => folderControllerFindAll({ signal, ...fetchOptions });

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof folderControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FolderControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof folderControllerFindAll>>
>;
export type FolderControllerFindAllQueryError = void;

export function useFolderControllerFindAll<
  TData = Awaited<ReturnType<typeof folderControllerFindAll>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof folderControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof folderControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFolderControllerFindAll<
  TData = Awaited<ReturnType<typeof folderControllerFindAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof folderControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof folderControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFolderControllerFindAll<
  TData = Awaited<ReturnType<typeof folderControllerFindAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFolderControllerFindAll<
  TData = Awaited<ReturnType<typeof folderControllerFindAll>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAll>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFolderControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type folderControllerFindAllWithFeedsResponse200 = {
  data: FolderWithFeedsOutDtoOutput[];
  status: 200;
};

export type folderControllerFindAllWithFeedsResponse401 = {
  data: void;
  status: 401;
};

export type folderControllerFindAllWithFeedsResponse500 = {
  data: void;
  status: 500;
};

export type folderControllerFindAllWithFeedsResponseSuccess =
  folderControllerFindAllWithFeedsResponse200 & {
    headers: Headers;
  };
export type folderControllerFindAllWithFeedsResponseError = (
  | folderControllerFindAllWithFeedsResponse401
  | folderControllerFindAllWithFeedsResponse500
) & {
  headers: Headers;
};

export type folderControllerFindAllWithFeedsResponse =
  | folderControllerFindAllWithFeedsResponseSuccess
  | folderControllerFindAllWithFeedsResponseError;

export const getFolderControllerFindAllWithFeedsUrl = () => {
  return `/folder/feeds`;
};

export const folderControllerFindAllWithFeeds = async (
  options?: RequestInit,
): Promise<folderControllerFindAllWithFeedsResponse> => {
  const res = await fetch(getFolderControllerFindAllWithFeedsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: folderControllerFindAllWithFeedsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as folderControllerFindAllWithFeedsResponse;
};

export const getFolderControllerFindAllWithFeedsQueryKey = () => {
  return [`/folder/feeds`] as const;
};

export const getFolderControllerFindAllWithFeedsQueryOptions = <
  TData = Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFolderControllerFindAllWithFeedsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>
  > = ({ signal }) =>
    folderControllerFindAllWithFeeds({ signal, ...fetchOptions });

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FolderControllerFindAllWithFeedsQueryResult = NonNullable<
  Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>
>;
export type FolderControllerFindAllWithFeedsQueryError = void;

export function useFolderControllerFindAllWithFeeds<
  TData = Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
          TError,
          Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFolderControllerFindAllWithFeeds<
  TData = Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
          TError,
          Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFolderControllerFindAllWithFeeds<
  TData = Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFolderControllerFindAllWithFeeds<
  TData = Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindAllWithFeeds>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFolderControllerFindAllWithFeedsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type folderControllerFindOneResponse200 = {
  data: FolderOutDtoOutput;
  status: 200;
};

export type folderControllerFindOneResponse401 = {
  data: void;
  status: 401;
};

export type folderControllerFindOneResponse500 = {
  data: void;
  status: 500;
};

export type folderControllerFindOneResponseSuccess =
  folderControllerFindOneResponse200 & {
    headers: Headers;
  };
export type folderControllerFindOneResponseError = (
  | folderControllerFindOneResponse401
  | folderControllerFindOneResponse500
) & {
  headers: Headers;
};

export type folderControllerFindOneResponse =
  | folderControllerFindOneResponseSuccess
  | folderControllerFindOneResponseError;

export const getFolderControllerFindOneUrl = (id: string) => {
  return `/folder/${id}`;
};

export const folderControllerFindOne = async (
  id: string,
  options?: RequestInit,
): Promise<folderControllerFindOneResponse> => {
  const res = await fetch(getFolderControllerFindOneUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: folderControllerFindOneResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as folderControllerFindOneResponse;
};

export const getFolderControllerFindOneQueryKey = (id: string) => {
  return [`/folder/${id}`] as const;
};

export const getFolderControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof folderControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindOne>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFolderControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof folderControllerFindOne>>
  > = ({ signal }) => folderControllerFindOne(id, { signal, ...fetchOptions });

  return {
    enabled: !!id,
    queryFn,
    queryKey,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof folderControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FolderControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof folderControllerFindOne>>
>;
export type FolderControllerFindOneQueryError = void;

export function useFolderControllerFindOne<
  TData = Awaited<ReturnType<typeof folderControllerFindOne>>,
  TError = void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof folderControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof folderControllerFindOne>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFolderControllerFindOne<
  TData = Awaited<ReturnType<typeof folderControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof folderControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof folderControllerFindOne>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFolderControllerFindOne<
  TData = Awaited<ReturnType<typeof folderControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindOne>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFolderControllerFindOne<
  TData = Awaited<ReturnType<typeof folderControllerFindOne>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof folderControllerFindOne>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFolderControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type folderControllerUpdateResponse200 = {
  data: FolderOutDtoOutput;
  status: 200;
};

export type folderControllerUpdateResponse401 = {
  data: void;
  status: 401;
};

export type folderControllerUpdateResponse500 = {
  data: void;
  status: 500;
};

export type folderControllerUpdateResponseSuccess =
  folderControllerUpdateResponse200 & {
    headers: Headers;
  };
export type folderControllerUpdateResponseError = (
  | folderControllerUpdateResponse401
  | folderControllerUpdateResponse500
) & {
  headers: Headers;
};

export type folderControllerUpdateResponse =
  | folderControllerUpdateResponseSuccess
  | folderControllerUpdateResponseError;

export const getFolderControllerUpdateUrl = (id: string) => {
  return `/folder/${id}`;
};

export const folderControllerUpdate = async (
  id: string,
  updateFolderDto: UpdateFolderDto,
  options?: RequestInit,
): Promise<folderControllerUpdateResponse> => {
  const res = await fetch(getFolderControllerUpdateUrl(id), {
    ...options,
    body: JSON.stringify(updateFolderDto),
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    method: 'PATCH',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: folderControllerUpdateResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as folderControllerUpdateResponse;
};

export const getFolderControllerUpdateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof folderControllerUpdate>>,
    TError,
    { id: string; data: UpdateFolderDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof folderControllerUpdate>>,
  TError,
  { id: string; data: UpdateFolderDto },
  TContext
> => {
  const mutationKey = ['folderControllerUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof folderControllerUpdate>>,
    { id: string; data: UpdateFolderDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return folderControllerUpdate(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FolderControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof folderControllerUpdate>>
>;
export type FolderControllerUpdateMutationBody = UpdateFolderDto;
export type FolderControllerUpdateMutationError = void;

export const useFolderControllerUpdate = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof folderControllerUpdate>>,
      TError,
      { id: string; data: UpdateFolderDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof folderControllerUpdate>>,
  TError,
  { id: string; data: UpdateFolderDto },
  TContext
> => {
  return useMutation(
    getFolderControllerUpdateMutationOptions(options),
    queryClient,
  );
};
export type folderControllerRemoveResponse204 = {
  data: void;
  status: 204;
};

export type folderControllerRemoveResponse401 = {
  data: void;
  status: 401;
};

export type folderControllerRemoveResponse500 = {
  data: void;
  status: 500;
};

export type folderControllerRemoveResponseSuccess =
  folderControllerRemoveResponse204 & {
    headers: Headers;
  };
export type folderControllerRemoveResponseError = (
  | folderControllerRemoveResponse401
  | folderControllerRemoveResponse500
) & {
  headers: Headers;
};

export type folderControllerRemoveResponse =
  | folderControllerRemoveResponseSuccess
  | folderControllerRemoveResponseError;

export const getFolderControllerRemoveUrl = (id: string) => {
  return `/folder/${id}`;
};

export const folderControllerRemove = async (
  id: string,
  options?: RequestInit,
): Promise<folderControllerRemoveResponse> => {
  const res = await fetch(getFolderControllerRemoveUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: folderControllerRemoveResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as folderControllerRemoveResponse;
};

export const getFolderControllerRemoveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof folderControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof folderControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['folderControllerRemove'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { fetch: undefined, mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof folderControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return folderControllerRemove(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FolderControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof folderControllerRemove>>
>;

export type FolderControllerRemoveMutationError = void;

export const useFolderControllerRemove = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof folderControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof folderControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getFolderControllerRemoveMutationOptions(options),
    queryClient,
  );
};
