/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/article': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getPagedArticles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getArticle'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/feed/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getPagedArticlesForFeed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/folder/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getAllArticlesForFolder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/hidden': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getHiddenArticles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getReadArticles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/read/feed/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getReadArticlesForFeed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/read/folder/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getReadArticlesForFolder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/readable/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ArticleController_requestFullArticleText'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_searchArticles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/starred': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getStarredArticles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/starred/feed/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getStarredArticlesForFeed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/starred/folder/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getStarredArticlesForFolder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/status/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['ArticleController_updateArticleStatus'];
    trace?: never;
  };
  '/article/unread': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getUnReadArticles'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/unread/feed/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getUnReadArticlesForFeed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/article/unread/folder/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ArticleController_getUnReadArticlesForFolder'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getLogin'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FeedController_findAll'];
    put?: never;
    post: operations['FeedController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feed/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FeedController_findOne'];
    put?: never;
    post?: never;
    delete: operations['FeedController_remove'];
    options?: never;
    head?: never;
    patch: operations['FeedController_update'];
    trace?: never;
  };
  '/feed/discover': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FeedController_discover'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feed/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FeedController_export'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feed/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FeedController_import'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/feed/mark-all-read/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FeedController_markAllRead'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/filter': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FilterController_findAll'];
    put?: never;
    post: operations['FilterController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/filter/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FilterController_findOne'];
    put: operations['FilterController_update'];
    post?: never;
    delete: operations['FilterController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/folder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FolderController_findAll'];
    put?: never;
    post: operations['FolderController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/folder/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FolderController_findOne'];
    put?: never;
    post?: never;
    delete: operations['FolderController_remove'];
    options?: never;
    head?: never;
    patch: operations['FolderController_update'];
    trace?: never;
  };
  '/folder/feeds': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FolderController_findAllWithFeeds'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_getProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getCategories'];
    put?: never;
    post: operations['MinifluxV1Controller_createCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/categories/{categoryId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_updateCategory'];
    post?: never;
    delete: operations['MinifluxV1Controller_deleteCategory'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/categories/{categoryId}/feeds': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getCategoryFeeds'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/categories/{categoryId}/mark-all-as-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_markCategoryAsRead'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/categories/{categoryId}/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_refreshCategoryFeeds'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/discover': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MinifluxV1Controller_discoverSubscriptions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/entries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getEntries'];
    put: operations['MinifluxV1Controller_updateEntries'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/entries/{entryId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getEntry'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/entries/{entryId}/bookmark': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_toggleBookmark'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/entries/{entryId}/fetch-content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_fetchOriginalArticle'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/entries/{entryId}/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MinifluxV1Controller_saveEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_export'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getFeeds'];
    put?: never;
    post: operations['MinifluxV1Controller_createFeed'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds/{feedId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getFeed'];
    put: operations['MinifluxV1Controller_updateFeed'];
    post?: never;
    delete: operations['MinifluxV1Controller_removeFeed'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds/{feedId}/icon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getFeedIcon'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds/{feedId}/mark-all-as-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_markFeedAsRead'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds/{feedId}/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_refreshFeed'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds/counters': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getFeedCounters'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/feeds/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_refreshAllFeeds'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/icons/{iconId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getIcon'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['MinifluxV1Controller_import'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/users/{userId}/mark-all-as-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['MinifluxV1Controller_markUserEntriesAsRead'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/miniflux/v1/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['MinifluxV1Controller_getVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readlater': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ReadlaterController_addBookmark'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readlater/configure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['ReadlaterController_createConfig'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ArticleDetailDto_Output: {
      authors: string[];
      categories: string[];
      /** @default [] */
      contentWarning: string[] | null;
      description: string | null;
      /** Format: uuid */
      feedId: string;
      feedTitle?: string;
      fullArticleHtml: string | null;
      fullArticleText: string | null;
      hash: string | null;
      /** Format: uuid */
      id: string;
      image: string | null;
      imageAlt: string | null;
      isBlurred?: boolean | null;
      isHidden?: boolean | null;
      isRead?: boolean | null;
      isStarred?: boolean | null;
      keywords: string[];
      minifluxId: number;
      /** Format: date-time */
      published: string;
      rawContent: string | null;
      readableHtml: string | null;
      readableText: string | null;
      title: string;
      updated?: string | null;
      url: string | null;
    };
    ArticleListDto_Output: {
      articles: {
        authors: string[];
        categories: string[];
        /** @default [] */
        contentWarning: string[] | null;
        description: string | null;
        /** Format: uuid */
        feedId: string;
        feedTitle?: string;
        fullArticleHtml: string | null;
        fullArticleText: string | null;
        hash: string | null;
        /** Format: uuid */
        id: string;
        image: string | null;
        imageAlt: string | null;
        isBlurred?: boolean | null;
        isHidden?: boolean | null;
        isRead?: boolean | null;
        isStarred?: boolean | null;
        keywords: string[];
        minifluxId: number;
        /** Format: date-time */
        published: string;
        rawContent: string | null;
        readableHtml: string | null;
        readableText: string | null;
        title: string;
        updated?: string | null;
        url: string | null;
      }[];
      cursor: string | null;
    };
    ArticleSearchDto_Output: {
      articles: {
        authors: string[];
        categories: string[];
        /** @default [] */
        contentWarning: string[] | null;
        description: string | null;
        feedId: string | null;
        feedTitle: string | null;
        fullArticleHtml: string | null;
        fullArticleText: string | null;
        hash: string | null;
        /** Format: uuid */
        id: string;
        image: string | null;
        imageAlt: string | null;
        /** @default false */
        isBlurred: boolean | null;
        /** @default false */
        isHidden: boolean | null;
        /** @default false */
        isRead: boolean | null;
        /** @default false */
        isStarred: boolean | null;
        keywords: string[];
        metaData:
          | (
              | (string | number | boolean | null)
              | {
                  [key: string]: unknown;
                }
              | unknown[]
            )
          | null;
        minifluxId: number;
        /** Format: date-time */
        published: string;
        rawContent: string | null;
        readableHtml: string | null;
        readableText: string | null;
        title: string;
        updated: string | null;
        url: string | null;
      }[];
    };
    ArticleStatusDto_Output: {
      /** Format: uuid */
      articleId: string;
      /** @default [] */
      contentWarning: string[] | null;
      isBlurred?: boolean;
      isHidden?: boolean;
      isRead?: boolean;
      isStarred?: boolean;
      userId: string;
    };
    CategoryOutDto_Output: {
      hide_globally: boolean;
      id: number;
      title: string;
      user_id: number;
    };
    CountersDto_Output: {
      reads: {
        [key: string]: number;
      };
      unreads: {
        [key: string]: number;
      };
    };
    CreateBookmarkDto: {
      /** Format: uri */
      url: string;
    };
    CreateCategoryDto: {
      title: string;
    };
    CreateConfigDto: {
      apiKey: string;
      /** Format: uri */
      apiURL: string;
    };
    CreateFeedDto: {
      category_id: number;
      /** Format: uri */
      feed_url: string;
    };
    CreateFilterDto: {
      action: {
        contentWarning: string | null;
        /** @enum {string} */
        type: 'blur' | 'markRead' | 'hide';
      };
      conditions: {
        authors?: string[];
        categories?: string[];
        contentContains?: string[];
        feeds?: string[];
        keywords?: string[];
        titleContains?: string[];
      };
      description?: string;
      /** @default true */
      isActive: boolean;
      name: string;
    };
    CreateFolderDto: {
      feedIds?: string[];
      name: string;
    };
    DiscoverDto: {
      password?: string;
      url: string;
      user_agent?: string;
      username?: string;
    };
    DiscoverOutDto_Output: {
      format: string;
      title: string | null;
      /** Format: uri */
      url: string;
    };
    EntriesListDto_Output: {
      entries: {
        author: string | null;
        authors: string[];
        categories: string[];
        comments_url: string;
        content: string;
        created_at: string;
        feed: {
          blocklist_rules: string;
          categories: string[];
          category: {
            /** @default 0 */
            id: number;
            /** @default  */
            title: string;
            user_id: number;
          };
          checked_at: string;
          crawler: boolean;
          /** @default false */
          disabled: boolean;
          etag_header: string;
          feed_host: string | null;
          /** Format: uri */
          feed_url: string;
          /** @default false */
          fetch_via_proxy: boolean;
          icon: {
            feed_id: number;
            icon_id: number;
          } | null;
          id: number;
          /** @default false */
          ignore_http_cache: boolean;
          keeplist_rules: string;
          last_modified_header: string;
          metaData:
            | (
                | (string | number | boolean | null)
                | {
                    [key: string]: unknown;
                  }
                | unknown[]
              )
            | null;
          parsing_error_count: number;
          parsing_error_message: string;
          password: string;
          rewrite_rules: string;
          scraper_rules: string;
          site_url: string;
          title: string;
          user_agent: string;
          user_id: number;
          username: string;
        };
        feed_id: number;
        /** Format: uuid */
        feedId: string;
        hash: string | null;
        id: number;
        image: string | null;
        imageAlt: string | null;
        metaData:
          | (
              | (string | number | boolean | null)
              | {
                  [key: string]: unknown;
                }
              | unknown[]
            )
          | null;
        published_at: string;
        reading_time: number;
        share_code: string;
        /** @default false */
        starred: boolean;
        status: string;
        title: string;
        url: string | null;
        user_id: number;
      }[];
      total: number;
    };
    EntryDto_Output: {
      author: string | null;
      authors: string[];
      categories: string[];
      comments_url: string;
      content: string;
      created_at: string;
      feed: {
        blocklist_rules: string;
        categories: string[];
        category: {
          /** @default 0 */
          id: number;
          /** @default  */
          title: string;
          user_id: number;
        };
        checked_at: string;
        crawler: boolean;
        /** @default false */
        disabled: boolean;
        etag_header: string;
        feed_host: string | null;
        /** Format: uri */
        feed_url: string;
        /** @default false */
        fetch_via_proxy: boolean;
        icon: {
          feed_id: number;
          icon_id: number;
        } | null;
        id: number;
        /** @default false */
        ignore_http_cache: boolean;
        keeplist_rules: string;
        last_modified_header: string;
        metaData:
          | (
              | (string | number | boolean | null)
              | {
                  [key: string]: unknown;
                }
              | unknown[]
            )
          | null;
        parsing_error_count: number;
        parsing_error_message: string;
        password: string;
        rewrite_rules: string;
        scraper_rules: string;
        site_url: string;
        title: string;
        user_agent: string;
        user_id: number;
        username: string;
      };
      feed_id: number;
      /** Format: uuid */
      feedId: string;
      hash: string | null;
      id: number;
      image: string | null;
      imageAlt: string | null;
      metaData:
        | (
            | (string | number | boolean | null)
            | {
                [key: string]: unknown;
              }
            | unknown[]
          )
        | null;
      published_at: string;
      reading_time: number;
      share_code: string;
      /** @default false */
      starred: boolean;
      status: string;
      title: string;
      url: string | null;
      user_id: number;
    };
    FeedMini_Output: {
      blocklist_rules: string;
      categories: string[];
      category: {
        /** @default 0 */
        id: number;
        /** @default  */
        title: string;
        user_id: number;
      };
      checked_at: string;
      crawler: boolean;
      /** @default false */
      disabled: boolean;
      etag_header: string;
      feed_host: string | null;
      /** Format: uri */
      feed_url: string;
      /** @default false */
      fetch_via_proxy: boolean;
      icon: {
        feed_id: number;
        icon_id: number;
      } | null;
      id: number;
      /** @default false */
      ignore_http_cache: boolean;
      keeplist_rules: string;
      last_modified_header: string;
      metaData:
        | (
            | (string | number | boolean | null)
            | {
                [key: string]: unknown;
              }
            | unknown[]
          )
        | null;
      parsing_error_count: number;
      parsing_error_message: string;
      password: string;
      rewrite_rules: string;
      scraper_rules: string;
      site_url: string;
      title: string;
      user_agent: string;
      user_id: number;
      username: string;
    };
    FeedOutWithCountsDto_Output: {
      categories: string[];
      crawler: boolean;
      etag_header: string;
      favicon: string | null;
      feed_host: string | null;
      folderId: string | null;
      /** Format: uuid */
      id: string;
      last_modified_header: string;
      /** Format: date-time */
      lastChecked: string;
      metaData:
        | (
            | (string | number | boolean | null)
            | {
                [key: string]: unknown;
              }
            | unknown[]
          )
        | null;
      minifluxId: number;
      parsingErrorCount: number;
      parsingErrorMessage: string | null;
      site_url: string;
      subtitle: string | null;
      title: string;
      unreadCount: number | null;
      updated?: string | null;
      url: string;
      userAgent: string | null;
    };
    FileDto: {
      /**
       * Format: binary
       * @description OPML file to import
       */
      file: Record<string, never>;
    };
    FilterOutDto_Output: {
      action: {
        contentWarning: string | null;
        /** @enum {string} */
        type: 'blur' | 'markRead' | 'hide';
      };
      conditions: {
        authors?: string[];
        categories?: string[];
        contentContains?: string[];
        feeds?: string[];
        keywords?: string[];
        titleContains?: string[];
      };
      description?: string;
      /** Format: uuid */
      id: string;
      /** @default true */
      isActive: boolean;
      name: string | null;
    };
    FolderOutDto_Output: {
      feedIds: string[];
      /** Format: uuid */
      id: string;
      name: string;
      userId: string;
    };
    FolderWithFeedsOutDto_Output: {
      feeds: {
        categories: string[];
        crawler: boolean;
        etag_header: string;
        favicon: string | null;
        feed_host: string | null;
        /** Format: uuid */
        id: string;
        last_modified_header: string;
        /** Format: date-time */
        lastChecked: string;
        metaData:
          | (
              | (string | number | boolean | null)
              | {
                  [key: string]: unknown;
                }
              | unknown[]
            )
          | null;
        parsingErrorCount: number;
        parsingErrorMessage: string | null;
        site_url: string;
        subtitle: string | null;
        title: string;
        updated?: string | null;
        url: string;
        userAgent: string | null;
      }[];
      /** Format: uuid */
      id: string;
      name: string;
      userId: string;
    };
    FullEntryContent_Output: {
      content: string;
    };
    HiddenArticleListDto_Output: {
      articles: {
        authors: string[];
        categories: string[];
        /** @default [] */
        contentWarning: string[] | null;
        description: string | null;
        /** Format: uuid */
        feedId: string;
        feedTitle?: string;
        fullArticleHtml: string | null;
        fullArticleText: string | null;
        hash: string | null;
        /** Format: uuid */
        id: string;
        image: string | null;
        imageAlt: string | null;
        isBlurred?: boolean | null;
        isHidden?: boolean | null;
        isRead?: boolean | null;
        isStarred?: boolean | null;
        keywords: string[];
        minifluxId: number;
        /** Format: date-time */
        published: string;
        rawContent: string | null;
        readableHtml: string | null;
        readableText: string | null;
        /** Format: uuid */
        ruleId: string;
        title: string;
        updated?: string | null;
        url: string | null;
      }[];
      cursor: string | null;
    };
    SubscribeFeedDto: {
      description?: string;
      folderName: string | null;
      /** Format: uri */
      url: string;
    };
    SubscriptionOutDto_Output: {
      description: string | null;
      /** Format: uuid */
      feedId: string;
      folderId: string | null;
      /** Format: uuid */
      id: string;
      userId: string;
    };
    UpdateEntriesDto: {
      entry_ids: number[];
      /** @enum {string} */
      status: 'read' | 'unread';
    };
    UpdateFeedDto: {
      description?: string;
      folderId: string | null;
    };
    UpdateFeedMiniDto: {
      category_id?: number;
      title?: string;
    };
    UpdateFilterDto: {
      action: {
        contentWarning?: string | null;
        /** @enum {string} */
        type?: 'blur' | 'markRead' | 'hide';
      };
      conditions: {
        authors?: string[];
        categories?: string[];
        contentContains?: string[];
        feeds?: string[];
        keywords?: string[];
        titleContains?: string[];
      };
      description?: string;
      /** @default true */
      isActive: boolean;
      name?: string;
    };
    UpdateFolderDto: {
      feedIds?: string[];
      name?: string;
    };
    UserSchemaDto_Output: {
      entries_per_page: number;
      entry_sorting_direction: string;
      entry_swipe: boolean;
      google_id: string;
      id: number;
      is_admin: boolean;
      keyboard_shortcuts: boolean;
      language: string;
      last_login_at: string;
      openid_connect_id: string;
      show_reading_time: boolean;
      stylesheet: string;
      theme: string;
      timezone: string;
      username: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ArticleController_getPagedArticles: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getArticle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleDetailDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getPagedArticlesForFeed: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getAllArticlesForFolder: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getHiddenArticles: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
        /** @description The id of the rule to filter by. Default is all. */
        ruleId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HiddenArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getReadArticles: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getReadArticlesForFeed: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getReadArticlesForFolder: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_requestFullArticleText: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_searchArticles: {
    parameters: {
      query: {
        /** @description The search query string. */
        query: string;
        /** @description The page offset. Default is 0. */
        offset?: number;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleSearchDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getStarredArticles: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getStarredArticlesForFeed: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getStarredArticlesForFolder: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_updateArticleStatus: {
    parameters: {
      query: {
        /** @description The status to update. Must be one of 'read', 'unread', 'starred', or 'unstarred'. */
        status: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleStatusDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getUnReadArticles: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getUnReadArticlesForFeed: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArticleController_getUnReadArticlesForFolder: {
    parameters: {
      query?: {
        /** @description The cursor for pagination. If not provided, starts from the beginning. */
        cursor?: string;
        /** @description The number of articles to return. Default is 10. */
        pageSize?: number;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArticleListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppController_getLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedOutWithCountsDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubscribeFeedDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscriptionOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedOutWithCountsDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Feed unsubscribed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFeedDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubscriptionOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_discover: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DiscoverDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DiscoverOutDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_export: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OPML file exported */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_import: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description OPML file to import */
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['FileDto'];
      };
    };
    responses: {
      /** @description Feed imported */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid OPML file */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FeedController_markAllRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilterController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FilterOutDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilterController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFilterDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FilterOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilterController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FilterOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilterController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFilterDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FilterOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FilterController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Filter deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FolderController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FolderOutDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FolderController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFolderDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FolderOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FolderController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FolderOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FolderController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Folder deleted successfully. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FolderController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFolderDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FolderOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FolderController_findAllWithFeeds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FolderWithFeedsOutDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Health Check is successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
            /** @example {} */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example ok */
            status?: string;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The Health Check is not successful */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       },
             *       "redis": {
             *         "message": "Could not connect",
             *         "status": "down"
             *       }
             *     }
             */
            details?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            };
            /**
             * @example {
             *       "redis": {
             *         "message": "Could not connect",
             *         "status": "down"
             *       }
             *     }
             */
            error?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /**
             * @example {
             *       "database": {
             *         "status": "up"
             *       }
             *     }
             */
            info?: {
              [key: string]: {
                status: string;
              } & {
                [key: string]: unknown;
              };
            } | null;
            /** @example error */
            status?: string;
          };
        };
      };
    };
  };
  AppController_getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getCategories: {
    parameters: {
      query: {
        counts: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOutDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_createCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_updateCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOutDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_deleteCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getCategoryFeeds: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedMini_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_markCategoryAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_refreshCategoryFeeds: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_discoverSubscriptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DiscoverDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DiscoverOutDto_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getEntries: {
    parameters: {
      query: {
        status: 'unread' | 'read';
        limit: number;
        offset?: number;
        order?:
          | 'id'
          | 'status'
          | 'published_at'
          | 'category_title'
          | 'category_id';
        direction?: 'asc' | 'desc';
        before?: number;
        after?: number;
        starred?: boolean;
        search?: string;
        category_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntriesListDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_updateEntries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEntriesDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EntryDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_toggleBookmark: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_fetchOriginalArticle: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FullEntryContent_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_saveEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_export: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OPML file exported */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getFeeds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedMini_Output'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_createFeed: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFeedDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getFeed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        feedId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeedMini_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_updateFeed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        feedId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFeedMiniDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_removeFeed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        feedId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getFeedIcon: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        feedId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_markFeedAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        feedId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_refreshFeed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        feedId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getFeedCounters: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CountersDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_refreshAllFeeds: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getIcon: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        iconId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_import: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description OPML file to import */
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['FileDto'];
      };
    };
    responses: {
      /** @description Feed imported */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid OPML file */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserSchemaDto_Output'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_markUserEntriesAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MinifluxV1Controller_getVersion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReadlaterController_addBookmark: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBookmarkDto'];
      };
    };
    responses: {
      /** @description Readlater item created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Readlater service not configured */
      412: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ReadlaterController_createConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConfigDto'];
      };
    };
    responses: {
      /** @description Created readlater configuration */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
