/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { ArticleSearchDtoOutputArticlesItemAuthorsItem } from './articleSearchDtoOutputArticlesItemAuthorsItem';
import type { ArticleSearchDtoOutputArticlesItemCategoriesItem } from './articleSearchDtoOutputArticlesItemCategoriesItem';
import type { ArticleSearchDtoOutputArticlesItemContributorsItem } from './articleSearchDtoOutputArticlesItemContributorsItem';
import type { ArticleSearchDtoOutputArticlesItemEnclosures } from './articleSearchDtoOutputArticlesItemEnclosures';
import type { ArticleSearchDtoOutputArticlesItemGeo } from './articleSearchDtoOutputArticlesItemGeo';
import type { ArticleSearchDtoOutputArticlesItemGuid } from './articleSearchDtoOutputArticlesItemGuid';
import type { ArticleSearchDtoOutputArticlesItemItunes } from './articleSearchDtoOutputArticlesItemItunes';
import type { ArticleSearchDtoOutputArticlesItemMedia } from './articleSearchDtoOutputArticlesItemMedia';
import type { ArticleSearchDtoOutputArticlesItemPodcast } from './articleSearchDtoOutputArticlesItemPodcast';
import type { ArticleSearchDtoOutputArticlesItemThread } from './articleSearchDtoOutputArticlesItemThread';
import type { ArticleSearchDtoOutputArticlesItemYoutube } from './articleSearchDtoOutputArticlesItemYoutube';

export type ArticleSearchDtoOutputArticlesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minimum 0 */
  minifluxId: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  url?: string | null;
  authors: ArticleSearchDtoOutputArticlesItemAuthorsItem[];
  contributors: ArticleSearchDtoOutputArticlesItemContributorsItem[];
  subject: string | null;
  publisher: string | null;
  contributor: string | null;
  format: string | null;
  language: string | null;
  rights: string | null;
  categories: ArticleSearchDtoOutputArticlesItemCategoriesItem[];
  description: string | null;
  comments: string | null;
  commentRss: string | null;
  geo: ArticleSearchDtoOutputArticlesItemGeo;
  hash: string | null;
  rawContent: string | null;
  readableHtml: string | null;
  readableText: string | null;
  fullArticleHtml: string | null;
  fullArticleText: string | null;
  encoded: string | null;
  keywords: string[];
  image: string | null;
  imageAlt: string | null;
  media: ArticleSearchDtoOutputArticlesItemMedia;
  youtube: ArticleSearchDtoOutputArticlesItemYoutube;
  podcast: ArticleSearchDtoOutputArticlesItemPodcast;
  thread: ArticleSearchDtoOutputArticlesItemThread;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  published: string;
  updated: string | null;
  guid: ArticleSearchDtoOutputArticlesItemGuid;
  enclosures: ArticleSearchDtoOutputArticlesItemEnclosures;
  itunes: ArticleSearchDtoOutputArticlesItemItunes;
  feedTitle: string | null;
  feedId: string | null;
  isRead: boolean | null;
  isStarred: boolean | null;
  isBlurred: boolean | null;
  isHidden: boolean | null;
  contentWarning: string[] | null;
};
