/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type ArticleSearchDtoOutputArticlesItemEnclosures =
  | {
      id: number;
      entry_id: number;
      url: string;
      /**
       * @minLength 1
       * @maxLength 255
       */
      mime_type: string;
      /** @minimum 0 */
      size: number;
      /** @minimum 0 */
      media_progression: number;
    }[]
  | null;
