/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { ArticleDetailDtoOutputAuthorsItem } from './articleDetailDtoOutputAuthorsItem';
import type { ArticleDetailDtoOutputCategoriesItem } from './articleDetailDtoOutputCategoriesItem';
import type { ArticleDetailDtoOutputContributorsItem } from './articleDetailDtoOutputContributorsItem';
import type { ArticleDetailDtoOutputEnclosures } from './articleDetailDtoOutputEnclosures';
import type { ArticleDetailDtoOutputGeo } from './articleDetailDtoOutputGeo';
import type { ArticleDetailDtoOutputGuid } from './articleDetailDtoOutputGuid';
import type { ArticleDetailDtoOutputItunes } from './articleDetailDtoOutputItunes';
import type { ArticleDetailDtoOutputMedia } from './articleDetailDtoOutputMedia';
import type { ArticleDetailDtoOutputPodcast } from './articleDetailDtoOutputPodcast';
import type { ArticleDetailDtoOutputThread } from './articleDetailDtoOutputThread';
import type { ArticleDetailDtoOutputYoutube } from './articleDetailDtoOutputYoutube';

export interface ArticleDetailDtoOutput {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  url?: string | null;
  authors: ArticleDetailDtoOutputAuthorsItem[];
  contributors: ArticleDetailDtoOutputContributorsItem[];
  subject: string | null;
  publisher: string | null;
  contributor: string | null;
  format: string | null;
  language: string | null;
  rights: string | null;
  categories: ArticleDetailDtoOutputCategoriesItem[];
  description: string | null;
  comments: string | null;
  commentRss: string | null;
  geo: ArticleDetailDtoOutputGeo;
  hash: string | null;
  rawContent: string | null;
  readableHtml: string | null;
  readableText: string | null;
  fullArticleHtml: string | null;
  fullArticleText: string | null;
  encoded: string | null;
  keywords: string[];
  image: string | null;
  imageAlt: string | null;
  media: ArticleDetailDtoOutputMedia;
  youtube: ArticleDetailDtoOutputYoutube;
  podcast: ArticleDetailDtoOutputPodcast;
  thread: ArticleDetailDtoOutputThread;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  published: string;
  updated: string | null;
  guid: ArticleDetailDtoOutputGuid;
  enclosures: ArticleDetailDtoOutputEnclosures;
  itunes: ArticleDetailDtoOutputItunes;
  /**
   * @minLength 1
   * @maxLength 255
   */
  feedTitle: string;
  isRead: boolean | null;
  isStarred: boolean | null;
  isBlurred: boolean | null;
  isHidden: boolean | null;
  contentWarning: string[] | null;
}
