/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type ArticleDetailDtoOutputMedia = {
  contents?: {
    url: string;
    fileSize?: number;
    type?: string;
    medium?: string;
    isDefault?: boolean;
    expression?: string;
    bitrate?: number;
    framerate?: number;
    samplingrate?: number;
    channels?: number;
    duration?: number;
    height?: number;
    width?: number;
    lang?: string;
  }[];
} | null;
