/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { CountersDtoOutputReads } from './countersDtoOutputReads';
import type { CountersDtoOutputUnreads } from './countersDtoOutputUnreads';

export interface CountersDtoOutput {
  reads: CountersDtoOutputReads;
  unreads: CountersDtoOutputUnreads;
}
