/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { CreateFilterDtoActionType } from './createFilterDtoActionType';

export type CreateFilterDtoAction = {
  type: CreateFilterDtoActionType;
  contentWarning: string | null;
};
