/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { EntryDtoOutputEnclosures } from './entryDtoOutputEnclosures';
import type { EntryDtoOutputFeed } from './entryDtoOutputFeed';
import type { EntryDtoOutputItunes } from './entryDtoOutputItunes';

export interface EntryDtoOutput {
  /** @minimum 0 */
  id: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  url?: string | null;
  hash: string | null;
  enclosures: EntryDtoOutputEnclosures;
  itunes: EntryDtoOutputItunes;
  /** @minimum 0 */
  user_id: number;
  /** @minimum 0 */
  feed_id: number;
  comments_url: string;
  author: string | null;
  content: string;
  published_at: string;
  created_at: string;
  status: string;
  share_code: string;
  starred: boolean;
  /** @minimum 0 */
  reading_time: number;
  feed: EntryDtoOutputFeed;
}
