/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { EntryDtoOutputFeedCategory } from './entryDtoOutputFeedCategory';
import type { EntryDtoOutputFeedIcon } from './entryDtoOutputFeedIcon';

export type EntryDtoOutputFeed = {
  title: string;
  site_url: string | null;
  etag_header: string;
  last_modified_header: string | null;
  crawler: boolean | null;
  /** @minimum 0 */
  id: number;
  /** @minimum 0 */
  user_id: number;
  checked_at: string;
  parsing_error_message: string;
  /** @minimum 0 */
  parsing_error_count: number;
  feed_url: string;
  icon: EntryDtoOutputFeedIcon;
  scraper_rules: string;
  rewrite_rules: string;
  blocklist_rules: string;
  keeplist_rules: string;
  user_agent: string;
  username: string;
  password: string;
  disabled: boolean;
  ignore_http_cache: boolean;
  fetch_via_proxy: boolean;
  category: EntryDtoOutputFeedCategory;
};
