/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type FeedOutWithCountsDtoOutputImage = {
  url: string;
  title?: string;
  link: string;
  description?: string;
  /** @minimum 0 */
  width?: number;
  /** @minimum 0 */
  height?: number;
} | null;
