/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type FeedOutWithCountsDtoOutputGeo = {
  point?: {
    lat: number;
    lng: number;
  };
  line?: {
    points: {
      lat: number;
      lng: number;
    }[];
  };
  polygon?: {
    points: {
      lat: number;
      lng: number;
    }[];
  };
  box?: {
    lowerCorner: {
      lat: number;
      lng: number;
    };
    upperCorner: {
      lat: number;
      lng: number;
    };
  };
  featureTypeTag?: string;
  relationshipTag?: string;
  featureName?: string;
  elev?: number;
  floor?: number;
  radius?: number;
} | null;
