/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { FilterOutDtoOutputAction } from './filterOutDtoOutputAction';
import type { FilterOutDtoOutputConditions } from './filterOutDtoOutputConditions';

export interface FilterOutDtoOutput {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string | null;
  /** @maxLength 1024 */
  description?: string;
  conditions: FilterOutDtoOutputConditions;
  isActive: boolean;
  action: FilterOutDtoOutputAction;
}
