/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { FolderWithFeedsOutDtoOutputFeedsItemAuthorsItem } from './folderWithFeedsOutDtoOutputFeedsItemAuthorsItem';
import type { FolderWithFeedsOutDtoOutputFeedsItemCategoriesItem } from './folderWithFeedsOutDtoOutputFeedsItemCategoriesItem';
import type { FolderWithFeedsOutDtoOutputFeedsItemContributorsItem } from './folderWithFeedsOutDtoOutputFeedsItemContributorsItem';
import type { FolderWithFeedsOutDtoOutputFeedsItemGeo } from './folderWithFeedsOutDtoOutputFeedsItemGeo';
import type { FolderWithFeedsOutDtoOutputFeedsItemImage } from './folderWithFeedsOutDtoOutputFeedsItemImage';
import type { FolderWithFeedsOutDtoOutputFeedsItemPodcast } from './folderWithFeedsOutDtoOutputFeedsItemPodcast';
import type { FolderWithFeedsOutDtoOutputFeedsItemYoutube } from './folderWithFeedsOutDtoOutputFeedsItemYoutube';

export type FolderWithFeedsOutDtoOutputFeedsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  subtitle: string | null;
  url: string;
  site_url: string | null;
  etag_header: string;
  last_modified_header: string | null;
  parsingErrorMessage: string | null;
  /** @minimum 0 */
  parsingErrorCount: number;
  userAgent: string | null;
  crawler: boolean | null;
  authors: FolderWithFeedsOutDtoOutputFeedsItemAuthorsItem[];
  contributors: FolderWithFeedsOutDtoOutputFeedsItemContributorsItem[];
  categories: FolderWithFeedsOutDtoOutputFeedsItemCategoriesItem[];
  copyright: string | null;
  image: FolderWithFeedsOutDtoOutputFeedsItemImage;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  lastChecked: string;
  updated: string | null;
  explicit: boolean | null;
  subject: string | null;
  updatePeriod: string | null;
  updateFrequency: number | null;
  updateBase: string | null;
  publisher: string | null;
  rights: string | null;
  youtube: FolderWithFeedsOutDtoOutputFeedsItemYoutube;
  podcast: FolderWithFeedsOutDtoOutputFeedsItemPodcast;
  geo: FolderWithFeedsOutDtoOutputFeedsItemGeo;
  favicon: string | null;
};
