/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck200Details } from './healthControllerCheck200Details';
import type { HealthControllerCheck200Error } from './healthControllerCheck200Error';
import type { HealthControllerCheck200Info } from './healthControllerCheck200Info';

export type HealthControllerCheck200 = {
  status?: string;
  info?: HealthControllerCheck200Info;
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};
