/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type MinifluxV1ControllerGetEntriesDirection =
  (typeof MinifluxV1ControllerGetEntriesDirection)[keyof typeof MinifluxV1ControllerGetEntriesDirection];

export const MinifluxV1ControllerGetEntriesDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
