/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type MinifluxV1ControllerGetEntriesOrder =
  (typeof MinifluxV1ControllerGetEntriesOrder)[keyof typeof MinifluxV1ControllerGetEntriesOrder];

export const MinifluxV1ControllerGetEntriesOrder = {
  category_id: 'category_id',
  category_title: 'category_title',
  id: 'id',
  published_at: 'published_at',
  status: 'status',
} as const;
