/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { NewSubscriptionDtoOutputAuthorsItem } from './newSubscriptionDtoOutputAuthorsItem';
import type { NewSubscriptionDtoOutputCategoriesItem } from './newSubscriptionDtoOutputCategoriesItem';
import type { NewSubscriptionDtoOutputContributorsItem } from './newSubscriptionDtoOutputContributorsItem';
import type { NewSubscriptionDtoOutputGeo } from './newSubscriptionDtoOutputGeo';
import type { NewSubscriptionDtoOutputImage } from './newSubscriptionDtoOutputImage';
import type { NewSubscriptionDtoOutputPodcast } from './newSubscriptionDtoOutputPodcast';
import type { NewSubscriptionDtoOutputSubscription } from './newSubscriptionDtoOutputSubscription';
import type { NewSubscriptionDtoOutputYoutube } from './newSubscriptionDtoOutputYoutube';

export interface NewSubscriptionDtoOutput {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minimum 0 */
  minifluxId: number;
  title: string;
  subtitle: string | null;
  url: string;
  site_url: string | null;
  etag_header: string;
  last_modified_header: string | null;
  parsingErrorMessage: string | null;
  /** @minimum 0 */
  parsingErrorCount: number;
  userAgent: string | null;
  crawler: boolean | null;
  authors: NewSubscriptionDtoOutputAuthorsItem[];
  contributors: NewSubscriptionDtoOutputContributorsItem[];
  categories: NewSubscriptionDtoOutputCategoriesItem[];
  copyright: string | null;
  image: NewSubscriptionDtoOutputImage;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  lastChecked: string;
  updated: string | null;
  explicit: boolean | null;
  subject: string | null;
  updatePeriod: string | null;
  updateFrequency: number | null;
  updateBase: string | null;
  publisher: string | null;
  rights: string | null;
  youtube: NewSubscriptionDtoOutputYoutube;
  podcast: NewSubscriptionDtoOutputPodcast;
  geo: NewSubscriptionDtoOutputGeo;
  subscription: NewSubscriptionDtoOutputSubscription;
}
