/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type NewSubscriptionDtoOutputPodcast = {
  locked?: {
    value: boolean;
    owner?: string;
  };
  fundings?: {
    url: string;
    display?: string;
  }[];
  persons?: {
    display: string;
    role?: string;
    group?: string;
    img?: string;
    href?: string;
  }[];
  location?: {
    display: string;
    geo?: string;
    osm?: string;
  };
  trailers?: {
    display: string;
    url: string;
    pubDate: string;
    /** @minimum 0 */
    length?: number;
    type?: string;
    season?: number;
  }[];
  guid?: string;
  value?: {
    type: string;
    method: string;
    /** @minimum 0 */
    suggested?: number;
    valueRecipients?: {
      name?: string;
      customKey?: string;
      customValue?: string;
      type: string;
      address: string;
      /** @minimum 0 */
      split: number;
      fee?: boolean;
    }[];
    valueTimeSplits?: {
      /** @minimum 0 */
      startTime: number;
      /** @minimum 0 */
      duration: number;
      /** @minimum 0 */
      remoteStartTime?: number;
      /** @minimum 0 */
      remotePercentage?: number;
      remoteItem?: {
        feedGuid: string;
        feedUrl?: string;
        itemGuid?: string;
        medium?: string;
      };
      valueRecipients?: {
        name?: string;
        customKey?: string;
        customValue?: string;
        type: string;
        address: string;
        /** @minimum 0 */
        split: number;
        fee?: boolean;
      }[];
    }[];
  };
  medium?: string;
  images?: {
    srcset?: string;
  };
  liveItems?: {
    status: string;
    /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
    start: string;
    /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
    end?: string;
    contentLinks?: {
      href: string;
      display?: string;
    }[];
  }[];
  blocks?: {
    value: boolean;
    id?: string;
  }[];
  txts?: {
    display: string;
    purpose?: string;
  }[];
  remoteItems?: {
    feedGuid: string;
    feedUrl?: string;
    itemGuid?: string;
    medium?: string;
  }[];
  podroll?: {
    remoteItems?: {
      feedGuid: string;
      feedUrl?: string;
      itemGuid?: string;
      medium?: string;
    }[];
  };
  updateFrequency?: {
    display: string;
    complete?: boolean;
    dtstart?: string;
    rrule?: string;
  };
  podping?: {
    usesPodping?: boolean;
  };
} | null;
