/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type UpdateFilterDtoActionType =
  (typeof UpdateFilterDtoActionType)[keyof typeof UpdateFilterDtoActionType];

export const UpdateFilterDtoActionType = {
  blur: 'blur',
  hide: 'hide',
  markRead: 'markRead',
} as const;
