/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export interface UpdateFolderDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  feedIds?: string[];
}
