/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import type { UpdateFilterDtoAction } from './updateFilterDtoAction';
import type { UpdateFilterDtoConditions } from './updateFilterDtoConditions';

export interface UpdateFilterDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /** @maxLength 1024 */
  description?: string;
  conditions: UpdateFilterDtoConditions;
  isActive?: boolean;
  action: UpdateFilterDtoAction;
}
