/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */

export type UpdateEntriesDtoStatus =
  (typeof UpdateEntriesDtoStatus)[keyof typeof UpdateEntriesDtoStatus];

export const UpdateEntriesDtoStatus = {
  read: 'read',
  unread: 'unread',
} as const;
