/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const minifluxV1ControllerDiscoverSubscriptionsBodyUrlMax = 2048;

export const minifluxV1ControllerDiscoverSubscriptionsBodyUsernameMax = 255;

export const minifluxV1ControllerDiscoverSubscriptionsBodyPasswordMax = 255;

export const minifluxV1ControllerDiscoverSubscriptionsBodyUserAgentMax = 255;

export const MinifluxV1ControllerDiscoverSubscriptionsBody = zod.object({
  password: zod
    .string()
    .min(1)
    .max(minifluxV1ControllerDiscoverSubscriptionsBodyPasswordMax)
    .optional(),
  url: zod
    .string()
    .min(1)
    .max(minifluxV1ControllerDiscoverSubscriptionsBodyUrlMax),
  user_agent: zod
    .string()
    .min(1)
    .max(minifluxV1ControllerDiscoverSubscriptionsBodyUserAgentMax)
    .optional(),
  username: zod
    .string()
    .min(1)
    .max(minifluxV1ControllerDiscoverSubscriptionsBodyUsernameMax)
    .optional(),
});

export const minifluxV1ControllerDiscoverSubscriptionsResponseTitleOneMax = 255;

export const minifluxV1ControllerDiscoverSubscriptionsResponseUrlMax = 2048;

export const MinifluxV1ControllerDiscoverSubscriptionsResponseItem = zod.object(
  {
    format: zod.string(),
    title: zod.union([
      zod
        .string()
        .min(1)
        .max(minifluxV1ControllerDiscoverSubscriptionsResponseTitleOneMax),
      zod.null(),
    ]),
    url: zod
      .url()
      .min(1)
      .max(minifluxV1ControllerDiscoverSubscriptionsResponseUrlMax),
  },
);
export const MinifluxV1ControllerDiscoverSubscriptionsResponse = zod.array(
  MinifluxV1ControllerDiscoverSubscriptionsResponseItem,
);

export const MinifluxV1ControllerImportBody = zod.object({
  file: zod.looseObject({}).describe('OPML file to import'),
});

export const minifluxV1ControllerGetFeedsResponseEtagHeaderDefault = ``;
export const minifluxV1ControllerGetFeedsResponseIdMin = 0;

export const minifluxV1ControllerGetFeedsResponseUserIdMin = 0;

export const minifluxV1ControllerGetFeedsResponseParsingErrorCountMin = 0;

export const minifluxV1ControllerGetFeedsResponseIconOneFeedIdMin = 0;

export const minifluxV1ControllerGetFeedsResponseIconOneIconIdMin = 0;

export const minifluxV1ControllerGetFeedsResponseDisabledDefault = false;
export const minifluxV1ControllerGetFeedsResponseIgnoreHttpCacheDefault = false;
export const minifluxV1ControllerGetFeedsResponseFetchViaProxyDefault = false;
export const minifluxV1ControllerGetFeedsResponseCategoryIdDefault = 0;
export const minifluxV1ControllerGetFeedsResponseCategoryUserIdMin = 0;

export const minifluxV1ControllerGetFeedsResponseCategoryTitleDefault = ``;

export const MinifluxV1ControllerGetFeedsResponseItem = zod.object({
  blocklist_rules: zod.string(),
  category: zod.object({
    id: zod
      .number()
      .default(minifluxV1ControllerGetFeedsResponseCategoryIdDefault),
    title: zod
      .string()
      .default(minifluxV1ControllerGetFeedsResponseCategoryTitleDefault),
    user_id: zod
      .number()
      .min(minifluxV1ControllerGetFeedsResponseCategoryUserIdMin),
  }),
  checked_at: zod.string(),
  crawler: zod.union([zod.boolean(), zod.null()]),
  disabled: zod
    .boolean()
    .default(minifluxV1ControllerGetFeedsResponseDisabledDefault),
  etag_header: zod
    .string()
    .default(minifluxV1ControllerGetFeedsResponseEtagHeaderDefault),
  feed_url: zod.url(),
  fetch_via_proxy: zod
    .boolean()
    .default(minifluxV1ControllerGetFeedsResponseFetchViaProxyDefault),
  icon: zod.union([
    zod.object({
      feed_id: zod
        .number()
        .min(minifluxV1ControllerGetFeedsResponseIconOneFeedIdMin),
      icon_id: zod
        .number()
        .min(minifluxV1ControllerGetFeedsResponseIconOneIconIdMin),
    }),
    zod.null(),
  ]),
  id: zod.number().min(minifluxV1ControllerGetFeedsResponseIdMin),
  ignore_http_cache: zod
    .boolean()
    .default(minifluxV1ControllerGetFeedsResponseIgnoreHttpCacheDefault),
  keeplist_rules: zod.string(),
  last_modified_header: zod.union([zod.string(), zod.null()]),
  parsing_error_count: zod
    .number()
    .min(minifluxV1ControllerGetFeedsResponseParsingErrorCountMin),
  parsing_error_message: zod.string(),
  password: zod.string(),
  rewrite_rules: zod.string(),
  scraper_rules: zod.string(),
  site_url: zod.union([zod.url(), zod.null()]),
  title: zod.string(),
  user_agent: zod.string(),
  user_id: zod.number().min(minifluxV1ControllerGetFeedsResponseUserIdMin),
  username: zod.string(),
});
export const MinifluxV1ControllerGetFeedsResponse = zod.array(
  MinifluxV1ControllerGetFeedsResponseItem,
);

export const minifluxV1ControllerCreateFeedBodyCategoryIdMin = 0;

export const MinifluxV1ControllerCreateFeedBody = zod.object({
  category_id: zod
    .number()
    .min(minifluxV1ControllerCreateFeedBodyCategoryIdMin),
  feed_url: zod.url(),
});

export const minifluxV1ControllerGetFeedCountersResponseReadsMinOne = 0;

export const minifluxV1ControllerGetFeedCountersResponseUnreadsMinOne = 0;

export const MinifluxV1ControllerGetFeedCountersResponse = zod.object({
  reads: zod.record(
    zod.string(),
    zod.number().min(minifluxV1ControllerGetFeedCountersResponseReadsMinOne),
  ),
  unreads: zod.record(
    zod.string(),
    zod.number().min(minifluxV1ControllerGetFeedCountersResponseUnreadsMinOne),
  ),
});

export const MinifluxV1ControllerGetFeedParams = zod.object({
  feedId: zod.number(),
});

export const minifluxV1ControllerGetFeedResponseEtagHeaderDefault = ``;
export const minifluxV1ControllerGetFeedResponseIdMin = 0;

export const minifluxV1ControllerGetFeedResponseUserIdMin = 0;

export const minifluxV1ControllerGetFeedResponseParsingErrorCountMin = 0;

export const minifluxV1ControllerGetFeedResponseIconOneFeedIdMin = 0;

export const minifluxV1ControllerGetFeedResponseIconOneIconIdMin = 0;

export const minifluxV1ControllerGetFeedResponseDisabledDefault = false;
export const minifluxV1ControllerGetFeedResponseIgnoreHttpCacheDefault = false;
export const minifluxV1ControllerGetFeedResponseFetchViaProxyDefault = false;
export const minifluxV1ControllerGetFeedResponseCategoryIdDefault = 0;
export const minifluxV1ControllerGetFeedResponseCategoryUserIdMin = 0;

export const minifluxV1ControllerGetFeedResponseCategoryTitleDefault = ``;

export const MinifluxV1ControllerGetFeedResponse = zod.object({
  blocklist_rules: zod.string(),
  category: zod.object({
    id: zod
      .number()
      .default(minifluxV1ControllerGetFeedResponseCategoryIdDefault),
    title: zod
      .string()
      .default(minifluxV1ControllerGetFeedResponseCategoryTitleDefault),
    user_id: zod
      .number()
      .min(minifluxV1ControllerGetFeedResponseCategoryUserIdMin),
  }),
  checked_at: zod.string(),
  crawler: zod.union([zod.boolean(), zod.null()]),
  disabled: zod
    .boolean()
    .default(minifluxV1ControllerGetFeedResponseDisabledDefault),
  etag_header: zod
    .string()
    .default(minifluxV1ControllerGetFeedResponseEtagHeaderDefault),
  feed_url: zod.url(),
  fetch_via_proxy: zod
    .boolean()
    .default(minifluxV1ControllerGetFeedResponseFetchViaProxyDefault),
  icon: zod.union([
    zod.object({
      feed_id: zod
        .number()
        .min(minifluxV1ControllerGetFeedResponseIconOneFeedIdMin),
      icon_id: zod
        .number()
        .min(minifluxV1ControllerGetFeedResponseIconOneIconIdMin),
    }),
    zod.null(),
  ]),
  id: zod.number().min(minifluxV1ControllerGetFeedResponseIdMin),
  ignore_http_cache: zod
    .boolean()
    .default(minifluxV1ControllerGetFeedResponseIgnoreHttpCacheDefault),
  keeplist_rules: zod.string(),
  last_modified_header: zod.union([zod.string(), zod.null()]),
  parsing_error_count: zod
    .number()
    .min(minifluxV1ControllerGetFeedResponseParsingErrorCountMin),
  parsing_error_message: zod.string(),
  password: zod.string(),
  rewrite_rules: zod.string(),
  scraper_rules: zod.string(),
  site_url: zod.union([zod.url(), zod.null()]),
  title: zod.string(),
  user_agent: zod.string(),
  user_id: zod.number().min(minifluxV1ControllerGetFeedResponseUserIdMin),
  username: zod.string(),
});

export const MinifluxV1ControllerUpdateFeedParams = zod.object({
  feedId: zod.number(),
});

export const minifluxV1ControllerUpdateFeedBodyTitleMax = 255;

export const minifluxV1ControllerUpdateFeedBodyCategoryIdMin = 0;

export const MinifluxV1ControllerUpdateFeedBody = zod.object({
  category_id: zod
    .number()
    .min(minifluxV1ControllerUpdateFeedBodyCategoryIdMin)
    .optional(),
  title: zod
    .string()
    .min(1)
    .max(minifluxV1ControllerUpdateFeedBodyTitleMax)
    .optional(),
});

export const MinifluxV1ControllerRemoveFeedParams = zod.object({
  feedId: zod.number(),
});

export const MinifluxV1ControllerRefreshFeedParams = zod.object({
  feedId: zod.number(),
});

export const MinifluxV1ControllerGetFeedIconParams = zod.object({
  feedId: zod.number(),
});

export const MinifluxV1ControllerMarkFeedAsReadParams = zod.object({
  feedId: zod.number(),
});

export const MinifluxV1ControllerGetEntriesQueryParams = zod.object({
  after: zod.number().optional(),
  before: zod.number().optional(),
  category_id: zod.number().optional(),
  direction: zod.enum(['asc', 'desc']).optional(),
  limit: zod.number(),
  offset: zod.number().optional(),
  order: zod
    .enum(['id', 'status', 'published_at', 'category_title', 'category_id'])
    .optional(),
  search: zod.string().optional(),
  starred: zod.boolean().optional(),
  status: zod.enum(['unread', 'read']),
});

export const minifluxV1ControllerGetEntriesResponseTotalMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemTitleMax = 255;

export const minifluxV1ControllerGetEntriesResponseEntriesItemHashOneRegExp =
  /^[0-9a-fA-F]{64}$/;
export const minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemMimeTypeMax = 255;

export const minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemSizeMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemMediaProgressionDefault = 0;
export const minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemMediaProgressionMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemUserIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemStarredDefault = false;
export const minifluxV1ControllerGetEntriesResponseEntriesItemReadingTimeMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedEtagHeaderDefault = ``;
export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedIdMinOne = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedUserIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedParsingErrorCountMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedIconOneFeedIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedIconOneIconIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedDisabledDefault = false;
export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedIgnoreHttpCacheDefault = false;
export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedFetchViaProxyDefault = false;
export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedCategoryIdDefault = 0;
export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedCategoryUserIdMin = 0;

export const minifluxV1ControllerGetEntriesResponseEntriesItemFeedCategoryTitleDefault = ``;

export const MinifluxV1ControllerGetEntriesResponse = zod.object({
  entries: zod.array(
    zod.object({
      author: zod.union([zod.string(), zod.null()]),
      comments_url: zod.string(),
      content: zod.string(),
      created_at: zod.string(),
      enclosures: zod.union([
        zod.array(
          zod.object({
            entry_id: zod.number(),
            id: zod.number(),
            media_progression: zod
              .number()
              .min(
                minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemMediaProgressionMin,
              )
              .default(
                minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemMediaProgressionDefault,
              ),
            mime_type: zod
              .string()
              .min(1)
              .max(
                minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemMimeTypeMax,
              ),
            size: zod
              .number()
              .min(
                minifluxV1ControllerGetEntriesResponseEntriesItemEnclosuresOneItemSizeMin,
              ),
            url: zod.url(),
          }),
        ),
        zod.null(),
      ]),
      feed: zod.object({
        blocklist_rules: zod.string(),
        category: zod.object({
          id: zod
            .number()
            .default(
              minifluxV1ControllerGetEntriesResponseEntriesItemFeedCategoryIdDefault,
            ),
          title: zod
            .string()
            .default(
              minifluxV1ControllerGetEntriesResponseEntriesItemFeedCategoryTitleDefault,
            ),
          user_id: zod
            .number()
            .min(
              minifluxV1ControllerGetEntriesResponseEntriesItemFeedCategoryUserIdMin,
            ),
        }),
        checked_at: zod.string(),
        crawler: zod.union([zod.boolean(), zod.null()]),
        disabled: zod
          .boolean()
          .default(
            minifluxV1ControllerGetEntriesResponseEntriesItemFeedDisabledDefault,
          ),
        etag_header: zod
          .string()
          .default(
            minifluxV1ControllerGetEntriesResponseEntriesItemFeedEtagHeaderDefault,
          ),
        feed_url: zod.url(),
        fetch_via_proxy: zod
          .boolean()
          .default(
            minifluxV1ControllerGetEntriesResponseEntriesItemFeedFetchViaProxyDefault,
          ),
        icon: zod.union([
          zod.object({
            feed_id: zod
              .number()
              .min(
                minifluxV1ControllerGetEntriesResponseEntriesItemFeedIconOneFeedIdMin,
              ),
            icon_id: zod
              .number()
              .min(
                minifluxV1ControllerGetEntriesResponseEntriesItemFeedIconOneIconIdMin,
              ),
          }),
          zod.null(),
        ]),
        id: zod
          .number()
          .min(minifluxV1ControllerGetEntriesResponseEntriesItemFeedIdMinOne),
        ignore_http_cache: zod
          .boolean()
          .default(
            minifluxV1ControllerGetEntriesResponseEntriesItemFeedIgnoreHttpCacheDefault,
          ),
        keeplist_rules: zod.string(),
        last_modified_header: zod.union([zod.string(), zod.null()]),
        parsing_error_count: zod
          .number()
          .min(
            minifluxV1ControllerGetEntriesResponseEntriesItemFeedParsingErrorCountMin,
          ),
        parsing_error_message: zod.string(),
        password: zod.string(),
        rewrite_rules: zod.string(),
        scraper_rules: zod.string(),
        site_url: zod.union([zod.url(), zod.null()]),
        title: zod.string(),
        user_agent: zod.string(),
        user_id: zod
          .number()
          .min(minifluxV1ControllerGetEntriesResponseEntriesItemFeedUserIdMin),
        username: zod.string(),
      }),
      feed_id: zod
        .number()
        .min(minifluxV1ControllerGetEntriesResponseEntriesItemFeedIdMin),
      hash: zod.union([
        zod.stringFormat(
          'sha256_hex',
          minifluxV1ControllerGetEntriesResponseEntriesItemHashOneRegExp,
        ),
        zod.null(),
      ]),
      id: zod
        .number()
        .min(minifluxV1ControllerGetEntriesResponseEntriesItemIdMin),
      itunes: zod.union([
        zod.object({
          block: zod.boolean().optional(),
          duration: zod.number().optional(),
          episode: zod.number().min(1).optional(),
          episodeType: zod.string().optional(),
          explicit: zod.boolean().optional(),
          image: zod.url().optional(),
          season: zod.number().min(1).optional(),
          title: zod.string().optional(),
        }),
        zod.null(),
      ]),
      published_at: zod.string(),
      reading_time: zod
        .number()
        .min(minifluxV1ControllerGetEntriesResponseEntriesItemReadingTimeMin),
      share_code: zod.string(),
      starred: zod
        .boolean()
        .default(
          minifluxV1ControllerGetEntriesResponseEntriesItemStarredDefault,
        ),
      status: zod.string(),
      title: zod
        .string()
        .min(1)
        .max(minifluxV1ControllerGetEntriesResponseEntriesItemTitleMax),
      url: zod.union([zod.url(), zod.null()]).optional(),
      user_id: zod
        .number()
        .min(minifluxV1ControllerGetEntriesResponseEntriesItemUserIdMin),
    }),
  ),
  total: zod.number().min(minifluxV1ControllerGetEntriesResponseTotalMin),
});

export const minifluxV1ControllerUpdateEntriesBodyEntryIdsItemMin = 0;

export const MinifluxV1ControllerUpdateEntriesBody = zod.object({
  entry_ids: zod.array(
    zod.number().min(minifluxV1ControllerUpdateEntriesBodyEntryIdsItemMin),
  ),
  status: zod.enum(['read', 'unread']),
});

export const MinifluxV1ControllerGetEntryParams = zod.object({
  entryId: zod.number(),
});

export const minifluxV1ControllerGetEntryResponseIdMin = 0;

export const minifluxV1ControllerGetEntryResponseTitleMax = 255;

export const minifluxV1ControllerGetEntryResponseHashOneRegExp =
  /^[0-9a-fA-F]{64}$/;
export const minifluxV1ControllerGetEntryResponseEnclosuresOneItemMimeTypeMax = 255;

export const minifluxV1ControllerGetEntryResponseEnclosuresOneItemSizeMin = 0;

export const minifluxV1ControllerGetEntryResponseEnclosuresOneItemMediaProgressionDefault = 0;
export const minifluxV1ControllerGetEntryResponseEnclosuresOneItemMediaProgressionMin = 0;

export const minifluxV1ControllerGetEntryResponseUserIdMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedIdMin = 0;

export const minifluxV1ControllerGetEntryResponseStarredDefault = false;
export const minifluxV1ControllerGetEntryResponseReadingTimeMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedEtagHeaderDefault = ``;
export const minifluxV1ControllerGetEntryResponseFeedIdMinOne = 0;

export const minifluxV1ControllerGetEntryResponseFeedUserIdMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedParsingErrorCountMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedIconOneFeedIdMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedIconOneIconIdMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedDisabledDefault = false;
export const minifluxV1ControllerGetEntryResponseFeedIgnoreHttpCacheDefault = false;
export const minifluxV1ControllerGetEntryResponseFeedFetchViaProxyDefault = false;
export const minifluxV1ControllerGetEntryResponseFeedCategoryIdDefault = 0;
export const minifluxV1ControllerGetEntryResponseFeedCategoryUserIdMin = 0;

export const minifluxV1ControllerGetEntryResponseFeedCategoryTitleDefault = ``;

export const MinifluxV1ControllerGetEntryResponse = zod.object({
  author: zod.union([zod.string(), zod.null()]),
  comments_url: zod.string(),
  content: zod.string(),
  created_at: zod.string(),
  enclosures: zod.union([
    zod.array(
      zod.object({
        entry_id: zod.number(),
        id: zod.number(),
        media_progression: zod
          .number()
          .min(
            minifluxV1ControllerGetEntryResponseEnclosuresOneItemMediaProgressionMin,
          )
          .default(
            minifluxV1ControllerGetEntryResponseEnclosuresOneItemMediaProgressionDefault,
          ),
        mime_type: zod
          .string()
          .min(1)
          .max(
            minifluxV1ControllerGetEntryResponseEnclosuresOneItemMimeTypeMax,
          ),
        size: zod
          .number()
          .min(minifluxV1ControllerGetEntryResponseEnclosuresOneItemSizeMin),
        url: zod.url(),
      }),
    ),
    zod.null(),
  ]),
  feed: zod.object({
    blocklist_rules: zod.string(),
    category: zod.object({
      id: zod
        .number()
        .default(minifluxV1ControllerGetEntryResponseFeedCategoryIdDefault),
      title: zod
        .string()
        .default(minifluxV1ControllerGetEntryResponseFeedCategoryTitleDefault),
      user_id: zod
        .number()
        .min(minifluxV1ControllerGetEntryResponseFeedCategoryUserIdMin),
    }),
    checked_at: zod.string(),
    crawler: zod.union([zod.boolean(), zod.null()]),
    disabled: zod
      .boolean()
      .default(minifluxV1ControllerGetEntryResponseFeedDisabledDefault),
    etag_header: zod
      .string()
      .default(minifluxV1ControllerGetEntryResponseFeedEtagHeaderDefault),
    feed_url: zod.url(),
    fetch_via_proxy: zod
      .boolean()
      .default(minifluxV1ControllerGetEntryResponseFeedFetchViaProxyDefault),
    icon: zod.union([
      zod.object({
        feed_id: zod
          .number()
          .min(minifluxV1ControllerGetEntryResponseFeedIconOneFeedIdMin),
        icon_id: zod
          .number()
          .min(minifluxV1ControllerGetEntryResponseFeedIconOneIconIdMin),
      }),
      zod.null(),
    ]),
    id: zod.number().min(minifluxV1ControllerGetEntryResponseFeedIdMinOne),
    ignore_http_cache: zod
      .boolean()
      .default(minifluxV1ControllerGetEntryResponseFeedIgnoreHttpCacheDefault),
    keeplist_rules: zod.string(),
    last_modified_header: zod.union([zod.string(), zod.null()]),
    parsing_error_count: zod
      .number()
      .min(minifluxV1ControllerGetEntryResponseFeedParsingErrorCountMin),
    parsing_error_message: zod.string(),
    password: zod.string(),
    rewrite_rules: zod.string(),
    scraper_rules: zod.string(),
    site_url: zod.union([zod.url(), zod.null()]),
    title: zod.string(),
    user_agent: zod.string(),
    user_id: zod
      .number()
      .min(minifluxV1ControllerGetEntryResponseFeedUserIdMin),
    username: zod.string(),
  }),
  feed_id: zod.number().min(minifluxV1ControllerGetEntryResponseFeedIdMin),
  hash: zod.union([
    zod.stringFormat(
      'sha256_hex',
      minifluxV1ControllerGetEntryResponseHashOneRegExp,
    ),
    zod.null(),
  ]),
  id: zod.number().min(minifluxV1ControllerGetEntryResponseIdMin),
  itunes: zod.union([
    zod.object({
      block: zod.boolean().optional(),
      duration: zod.number().optional(),
      episode: zod.number().min(1).optional(),
      episodeType: zod.string().optional(),
      explicit: zod.boolean().optional(),
      image: zod.url().optional(),
      season: zod.number().min(1).optional(),
      title: zod.string().optional(),
    }),
    zod.null(),
  ]),
  published_at: zod.string(),
  reading_time: zod
    .number()
    .min(minifluxV1ControllerGetEntryResponseReadingTimeMin),
  share_code: zod.string(),
  starred: zod
    .boolean()
    .default(minifluxV1ControllerGetEntryResponseStarredDefault),
  status: zod.string(),
  title: zod.string().min(1).max(minifluxV1ControllerGetEntryResponseTitleMax),
  url: zod.union([zod.url(), zod.null()]).optional(),
  user_id: zod.number().min(minifluxV1ControllerGetEntryResponseUserIdMin),
});

export const MinifluxV1ControllerSaveEntryParams = zod.object({
  entryId: zod.number(),
});

export const MinifluxV1ControllerToggleBookmarkParams = zod.object({
  entryId: zod.number(),
});

export const MinifluxV1ControllerFetchOriginalArticleParams = zod.object({
  entryId: zod.number(),
});

export const MinifluxV1ControllerFetchOriginalArticleResponse = zod.object({
  content: zod.string(),
});

export const MinifluxV1ControllerGetCategoriesQueryParams = zod.object({
  counts: zod.boolean(),
});

export const MinifluxV1ControllerGetCategoriesResponseItem = zod.object({
  hide_globally: zod.boolean(),
  id: zod.number(),
  title: zod.string(),
  user_id: zod.number(),
});
export const MinifluxV1ControllerGetCategoriesResponse = zod.array(
  MinifluxV1ControllerGetCategoriesResponseItem,
);

export const MinifluxV1ControllerCreateCategoryBody = zod.object({
  title: zod.string(),
});

export const MinifluxV1ControllerUpdateCategoryParams = zod.object({
  categoryId: zod.number(),
});

export const MinifluxV1ControllerUpdateCategoryBody = zod.object({
  title: zod.string(),
});

export const MinifluxV1ControllerDeleteCategoryParams = zod.object({
  categoryId: zod.number(),
});

export const MinifluxV1ControllerGetCategoryFeedsParams = zod.object({
  categoryId: zod.number(),
});

export const minifluxV1ControllerGetCategoryFeedsResponseEtagHeaderDefault = ``;
export const minifluxV1ControllerGetCategoryFeedsResponseIdMin = 0;

export const minifluxV1ControllerGetCategoryFeedsResponseUserIdMin = 0;

export const minifluxV1ControllerGetCategoryFeedsResponseParsingErrorCountMin = 0;

export const minifluxV1ControllerGetCategoryFeedsResponseIconOneFeedIdMin = 0;

export const minifluxV1ControllerGetCategoryFeedsResponseIconOneIconIdMin = 0;

export const minifluxV1ControllerGetCategoryFeedsResponseDisabledDefault = false;
export const minifluxV1ControllerGetCategoryFeedsResponseIgnoreHttpCacheDefault = false;
export const minifluxV1ControllerGetCategoryFeedsResponseFetchViaProxyDefault = false;
export const minifluxV1ControllerGetCategoryFeedsResponseCategoryIdDefault = 0;
export const minifluxV1ControllerGetCategoryFeedsResponseCategoryUserIdMin = 0;

export const minifluxV1ControllerGetCategoryFeedsResponseCategoryTitleDefault = ``;

export const MinifluxV1ControllerGetCategoryFeedsResponseItem = zod.object({
  blocklist_rules: zod.string(),
  category: zod.object({
    id: zod
      .number()
      .default(minifluxV1ControllerGetCategoryFeedsResponseCategoryIdDefault),
    title: zod
      .string()
      .default(
        minifluxV1ControllerGetCategoryFeedsResponseCategoryTitleDefault,
      ),
    user_id: zod
      .number()
      .min(minifluxV1ControllerGetCategoryFeedsResponseCategoryUserIdMin),
  }),
  checked_at: zod.string(),
  crawler: zod.union([zod.boolean(), zod.null()]),
  disabled: zod
    .boolean()
    .default(minifluxV1ControllerGetCategoryFeedsResponseDisabledDefault),
  etag_header: zod
    .string()
    .default(minifluxV1ControllerGetCategoryFeedsResponseEtagHeaderDefault),
  feed_url: zod.url(),
  fetch_via_proxy: zod
    .boolean()
    .default(minifluxV1ControllerGetCategoryFeedsResponseFetchViaProxyDefault),
  icon: zod.union([
    zod.object({
      feed_id: zod
        .number()
        .min(minifluxV1ControllerGetCategoryFeedsResponseIconOneFeedIdMin),
      icon_id: zod
        .number()
        .min(minifluxV1ControllerGetCategoryFeedsResponseIconOneIconIdMin),
    }),
    zod.null(),
  ]),
  id: zod.number().min(minifluxV1ControllerGetCategoryFeedsResponseIdMin),
  ignore_http_cache: zod
    .boolean()
    .default(
      minifluxV1ControllerGetCategoryFeedsResponseIgnoreHttpCacheDefault,
    ),
  keeplist_rules: zod.string(),
  last_modified_header: zod.union([zod.string(), zod.null()]),
  parsing_error_count: zod
    .number()
    .min(minifluxV1ControllerGetCategoryFeedsResponseParsingErrorCountMin),
  parsing_error_message: zod.string(),
  password: zod.string(),
  rewrite_rules: zod.string(),
  scraper_rules: zod.string(),
  site_url: zod.union([zod.url(), zod.null()]),
  title: zod.string(),
  user_agent: zod.string(),
  user_id: zod
    .number()
    .min(minifluxV1ControllerGetCategoryFeedsResponseUserIdMin),
  username: zod.string(),
});
export const MinifluxV1ControllerGetCategoryFeedsResponse = zod.array(
  MinifluxV1ControllerGetCategoryFeedsResponseItem,
);

export const MinifluxV1ControllerMarkCategoryAsReadParams = zod.object({
  categoryId: zod.number(),
});

export const MinifluxV1ControllerRefreshCategoryFeedsParams = zod.object({
  categoryId: zod.number(),
});

export const MinifluxV1ControllerGetCurrentUserResponse = zod.object({
  entries_per_page: zod.number(),
  entry_sorting_direction: zod.string(),
  entry_swipe: zod.boolean(),
  google_id: zod.string(),
  id: zod.number(),
  is_admin: zod.boolean(),
  keyboard_shortcuts: zod.boolean(),
  language: zod.string(),
  last_login_at: zod.string(),
  openid_connect_id: zod.string(),
  show_reading_time: zod.boolean(),
  stylesheet: zod.string(),
  theme: zod.string(),
  timezone: zod.string(),
  username: zod.string(),
});

export const MinifluxV1ControllerMarkUserEntriesAsReadParams = zod.object({
  userId: zod.number(),
});

export const MinifluxV1ControllerGetIconParams = zod.object({
  iconId: zod.number(),
});
