/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Lionsmane API
 * the api for lionsmane
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const folderControllerCreateBodyNameMax = 255;

export const folderControllerCreateBodyFeedIdsItemRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FolderControllerCreateBody = zod.object({
  feedIds: zod
    .array(
      zod
        .uuid()
        .stringFormat('uuid', folderControllerCreateBodyFeedIdsItemRegExp),
    )
    .optional(),
  name: zod.string().min(1).max(folderControllerCreateBodyNameMax),
});

export const folderControllerFindAllResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const folderControllerFindAllResponseNameMax = 255;

export const folderControllerFindAllResponseFeedIdsItemRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FolderControllerFindAllResponseItem = zod.object({
  feedIds: zod.array(
    zod
      .uuid()
      .stringFormat('uuid', folderControllerFindAllResponseFeedIdsItemRegExp),
  ),
  id: zod.uuid().stringFormat('uuid', folderControllerFindAllResponseIdRegExp),
  name: zod.string().min(1).max(folderControllerFindAllResponseNameMax),
  userId: zod.string(),
});
export const FolderControllerFindAllResponse = zod.array(
  FolderControllerFindAllResponseItem,
);

export const folderControllerFindAllWithFeedsResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const folderControllerFindAllWithFeedsResponseNameMax = 255;

export const folderControllerFindAllWithFeedsResponseFeedsItemIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const folderControllerFindAllWithFeedsResponseFeedsItemEtagHeaderDefault = ``;
export const folderControllerFindAllWithFeedsResponseFeedsItemParsingErrorCountDefault = 0;
export const folderControllerFindAllWithFeedsResponseFeedsItemParsingErrorCountMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemAuthorsItemEmailRegExp =
  /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9-]*\.)+[A-Za-z]{2,}$/;
export const folderControllerFindAllWithFeedsResponseFeedsItemAuthorsDefault =
  [];
export const folderControllerFindAllWithFeedsResponseFeedsItemContributorsItemEmailRegExp =
  /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9-]*\.)+[A-Za-z]{2,}$/;
export const folderControllerFindAllWithFeedsResponseFeedsItemContributorsDefault =
  [];
export const folderControllerFindAllWithFeedsResponseFeedsItemCategoriesDefault =
  [];
export const folderControllerFindAllWithFeedsResponseFeedsItemImageOneWidthMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemImageOneHeightMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemLastCheckedRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const folderControllerFindAllWithFeedsResponseFeedsItemUpdatedOneRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneTrailersItemLengthMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueSuggestedMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueRecipientsItemSplitMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemStartTimeMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemDurationMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemRemoteStartTimeMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemRemotePercentageMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemValueRecipientsItemSplitMin = 0;

export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneLiveItemsItemStartRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;
export const folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneLiveItemsItemEndRegExp =
  /^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/;

export const FolderControllerFindAllWithFeedsResponseItem = zod.object({
  feeds: zod.array(
    zod.object({
      authors: zod
        .array(
          zod.object({
            email: zod
              .email()
              .stringFormat(
                'email',
                folderControllerFindAllWithFeedsResponseFeedsItemAuthorsItemEmailRegExp,
              )
              .optional(),
            name: zod.string(),
            uri: zod.url().optional(),
          }),
        )
        .default(
          folderControllerFindAllWithFeedsResponseFeedsItemAuthorsDefault,
        ),
      categories: zod
        .array(
          zod.object({
            label: zod.string().optional(),
            scheme: zod.string().optional(),
            term: zod.string().optional(),
          }),
        )
        .default(
          folderControllerFindAllWithFeedsResponseFeedsItemCategoriesDefault,
        ),
      contributors: zod
        .array(
          zod.object({
            email: zod
              .email()
              .stringFormat(
                'email',
                folderControllerFindAllWithFeedsResponseFeedsItemContributorsItemEmailRegExp,
              )
              .optional(),
            name: zod.string(),
            uri: zod.url().optional(),
          }),
        )
        .default(
          folderControllerFindAllWithFeedsResponseFeedsItemContributorsDefault,
        ),
      copyright: zod.union([zod.string(), zod.null()]),
      crawler: zod.union([zod.boolean(), zod.null()]),
      etag_header: zod
        .string()
        .default(
          folderControllerFindAllWithFeedsResponseFeedsItemEtagHeaderDefault,
        ),
      explicit: zod.union([zod.boolean(), zod.null()]),
      favicon: zod.union([zod.url(), zod.null()]),
      geo: zod.union([
        zod.object({
          box: zod
            .object({
              lowerCorner: zod.object({
                lat: zod.number(),
                lng: zod.number(),
              }),
              upperCorner: zod.object({
                lat: zod.number(),
                lng: zod.number(),
              }),
            })
            .optional(),
          elev: zod.number().optional(),
          featureName: zod.string().optional(),
          featureTypeTag: zod.string().optional(),
          floor: zod.number().optional(),
          line: zod
            .object({
              points: zod.array(
                zod.object({
                  lat: zod.number(),
                  lng: zod.number(),
                }),
              ),
            })
            .optional(),
          point: zod
            .object({
              lat: zod.number(),
              lng: zod.number(),
            })
            .optional(),
          polygon: zod
            .object({
              points: zod.array(
                zod.object({
                  lat: zod.number(),
                  lng: zod.number(),
                }),
              ),
            })
            .optional(),
          radius: zod.number().optional(),
          relationshipTag: zod.string().optional(),
        }),
        zod.null(),
      ]),
      id: zod
        .uuid()
        .stringFormat(
          'uuid',
          folderControllerFindAllWithFeedsResponseFeedsItemIdRegExp,
        ),
      image: zod.union([
        zod.object({
          description: zod.string().optional(),
          height: zod
            .number()
            .min(
              folderControllerFindAllWithFeedsResponseFeedsItemImageOneHeightMin,
            )
            .optional(),
          link: zod.url(),
          title: zod.string().optional(),
          url: zod.url(),
          width: zod
            .number()
            .min(
              folderControllerFindAllWithFeedsResponseFeedsItemImageOneWidthMin,
            )
            .optional(),
        }),
        zod.null(),
      ]),
      last_modified_header: zod.union([zod.string(), zod.null()]),
      lastChecked: zod.iso
        .datetime({})
        .stringFormat(
          'date-time',
          folderControllerFindAllWithFeedsResponseFeedsItemLastCheckedRegExp,
        ),
      parsingErrorCount: zod
        .number()
        .min(
          folderControllerFindAllWithFeedsResponseFeedsItemParsingErrorCountMin,
        )
        .default(
          folderControllerFindAllWithFeedsResponseFeedsItemParsingErrorCountDefault,
        ),
      parsingErrorMessage: zod.union([zod.string(), zod.null()]),
      podcast: zod.union([
        zod.object({
          blocks: zod
            .array(
              zod.object({
                id: zod.string().optional(),
                value: zod.boolean(),
              }),
            )
            .optional(),
          fundings: zod
            .array(
              zod.object({
                display: zod.string().optional(),
                url: zod.url(),
              }),
            )
            .optional(),
          guid: zod.string().optional(),
          images: zod
            .object({
              srcset: zod.string().optional(),
            })
            .optional(),
          liveItems: zod
            .array(
              zod.object({
                contentLinks: zod
                  .array(
                    zod.object({
                      display: zod.string().optional(),
                      href: zod.url(),
                    }),
                  )
                  .optional(),
                end: zod.iso
                  .datetime({})
                  .stringFormat(
                    'date-time',
                    folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneLiveItemsItemEndRegExp,
                  )
                  .optional(),
                start: zod.iso
                  .datetime({})
                  .stringFormat(
                    'date-time',
                    folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneLiveItemsItemStartRegExp,
                  ),
                status: zod.string(),
              }),
            )
            .optional(),
          location: zod
            .object({
              display: zod.string(),
              geo: zod.string().optional(),
              osm: zod.string().optional(),
            })
            .optional(),
          locked: zod
            .object({
              owner: zod.string().optional(),
              value: zod.boolean(),
            })
            .optional(),
          medium: zod.string().optional(),
          persons: zod
            .array(
              zod.object({
                display: zod.string(),
                group: zod.string().optional(),
                href: zod.url().optional(),
                img: zod.url().optional(),
                role: zod.string().optional(),
              }),
            )
            .optional(),
          podping: zod
            .object({
              usesPodping: zod.boolean().optional(),
            })
            .optional(),
          podroll: zod
            .object({
              remoteItems: zod
                .array(
                  zod.object({
                    feedGuid: zod.string(),
                    feedUrl: zod.url().optional(),
                    itemGuid: zod.string().optional(),
                    medium: zod.string().optional(),
                  }),
                )
                .optional(),
            })
            .optional(),
          remoteItems: zod
            .array(
              zod.object({
                feedGuid: zod.string(),
                feedUrl: zod.url().optional(),
                itemGuid: zod.string().optional(),
                medium: zod.string().optional(),
              }),
            )
            .optional(),
          trailers: zod
            .array(
              zod.object({
                display: zod.string(),
                length: zod
                  .number()
                  .min(
                    folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneTrailersItemLengthMin,
                  )
                  .optional(),
                pubDate: zod.string(),
                season: zod.number().optional(),
                type: zod.string().optional(),
                url: zod.url(),
              }),
            )
            .optional(),
          txts: zod
            .array(
              zod.object({
                display: zod.string(),
                purpose: zod.string().optional(),
              }),
            )
            .optional(),
          updateFrequency: zod
            .object({
              complete: zod.boolean().optional(),
              display: zod.string(),
              dtstart: zod.string().optional(),
              rrule: zod.string().optional(),
            })
            .optional(),
          value: zod
            .object({
              method: zod.string(),
              suggested: zod
                .number()
                .min(
                  folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueSuggestedMin,
                )
                .optional(),
              type: zod.string(),
              valueRecipients: zod
                .array(
                  zod.object({
                    address: zod.string(),
                    customKey: zod.string().optional(),
                    customValue: zod.string().optional(),
                    fee: zod.boolean().optional(),
                    name: zod.string().optional(),
                    split: zod
                      .number()
                      .min(
                        folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueRecipientsItemSplitMin,
                      ),
                    type: zod.string(),
                  }),
                )
                .optional(),
              valueTimeSplits: zod
                .array(
                  zod.object({
                    duration: zod
                      .number()
                      .min(
                        folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemDurationMin,
                      ),
                    remoteItem: zod
                      .object({
                        feedGuid: zod.string(),
                        feedUrl: zod.url().optional(),
                        itemGuid: zod.string().optional(),
                        medium: zod.string().optional(),
                      })
                      .optional(),
                    remotePercentage: zod
                      .number()
                      .min(
                        folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemRemotePercentageMin,
                      )
                      .optional(),
                    remoteStartTime: zod
                      .number()
                      .min(
                        folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemRemoteStartTimeMin,
                      )
                      .optional(),
                    startTime: zod
                      .number()
                      .min(
                        folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemStartTimeMin,
                      ),
                    valueRecipients: zod
                      .array(
                        zod.object({
                          address: zod.string(),
                          customKey: zod.string().optional(),
                          customValue: zod.string().optional(),
                          fee: zod.boolean().optional(),
                          name: zod.string().optional(),
                          split: zod
                            .number()
                            .min(
                              folderControllerFindAllWithFeedsResponseFeedsItemPodcastOneValueValueTimeSplitsItemValueRecipientsItemSplitMin,
                            ),
                          type: zod.string(),
                        }),
                      )
                      .optional(),
                  }),
                )
                .optional(),
            })
            .optional(),
        }),
        zod.null(),
      ]),
      publisher: zod.union([zod.string(), zod.null()]),
      rights: zod.union([zod.string(), zod.null()]),
      site_url: zod.union([zod.url(), zod.null()]),
      subject: zod.union([zod.string(), zod.null()]),
      subtitle: zod.union([zod.string(), zod.null()]),
      title: zod.string(),
      updateBase: zod.union([zod.string(), zod.null()]),
      updated: zod.union([
        zod.iso
          .datetime({})
          .stringFormat(
            'date-time',
            folderControllerFindAllWithFeedsResponseFeedsItemUpdatedOneRegExp,
          ),
        zod.null(),
      ]),
      updateFrequency: zod.union([zod.number(), zod.null()]),
      updatePeriod: zod.union([zod.string(), zod.null()]),
      url: zod.url(),
      userAgent: zod.union([zod.string(), zod.null()]),
      youtube: zod.union([
        zod.object({
          channelId: zod.string().optional(),
          playlistId: zod.string().optional(),
        }),
        zod.null(),
      ]),
    }),
  ),
  id: zod
    .uuid()
    .stringFormat('uuid', folderControllerFindAllWithFeedsResponseIdRegExp),
  name: zod
    .string()
    .min(1)
    .max(folderControllerFindAllWithFeedsResponseNameMax),
  userId: zod.string(),
});
export const FolderControllerFindAllWithFeedsResponse = zod.array(
  FolderControllerFindAllWithFeedsResponseItem,
);

export const FolderControllerFindOneParams = zod.object({
  id: zod.string(),
});

export const folderControllerFindOneResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const folderControllerFindOneResponseNameMax = 255;

export const folderControllerFindOneResponseFeedIdsItemRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FolderControllerFindOneResponse = zod.object({
  feedIds: zod.array(
    zod
      .uuid()
      .stringFormat('uuid', folderControllerFindOneResponseFeedIdsItemRegExp),
  ),
  id: zod.uuid().stringFormat('uuid', folderControllerFindOneResponseIdRegExp),
  name: zod.string().min(1).max(folderControllerFindOneResponseNameMax),
  userId: zod.string(),
});

export const FolderControllerUpdateParams = zod.object({
  id: zod.string(),
});

export const folderControllerUpdateBodyNameMax = 255;

export const folderControllerUpdateBodyFeedIdsItemRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FolderControllerUpdateBody = zod.object({
  feedIds: zod
    .array(
      zod
        .uuid()
        .stringFormat('uuid', folderControllerUpdateBodyFeedIdsItemRegExp),
    )
    .optional(),
  name: zod.string().min(1).max(folderControllerUpdateBodyNameMax).optional(),
});

export const folderControllerUpdateResponseIdRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;
export const folderControllerUpdateResponseNameMax = 255;

export const folderControllerUpdateResponseFeedIdsItemRegExp =
  /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/;

export const FolderControllerUpdateResponse = zod.object({
  feedIds: zod.array(
    zod
      .uuid()
      .stringFormat('uuid', folderControllerUpdateResponseFeedIdsItemRegExp),
  ),
  id: zod.uuid().stringFormat('uuid', folderControllerUpdateResponseIdRegExp),
  name: zod.string().min(1).max(folderControllerUpdateResponseNameMax),
  userId: zod.string(),
});

export const FolderControllerRemoveParams = zod.object({
  id: zod.string(),
});
