when:
  - event: push
    branch: main

steps:
  - name: playwright
    image: mcr.microsoft.com/playwright:v1.55.0-noble
    directory: lionsmane-fe
    commands:
      - npm ci
      - npx playwright install --with-deps
      - npx playwright test --reporter=github
